package com.example.gymapp.util

/** Offline Russian translations for dynamic strings that cannot use Android resources. */
object RussianText {
    private val exact = mapOf(
        "Abs" to "Пресс",
        "Accumulate 10000 total volume." to "Набери общий объём 10 000.",
        "Adductors" to "Приводные",
        "All time" to "За все время",
        "Apex" to "Апекс",
        "Ascendant" to "Вознесенный",
        "Assisted Pull Up" to "Подтягивание в гравитроне",
        "Back, biceps and forearms have the oldest recent work." to "Спина, бицепс и предплечье дольше всего не были в работе.",
        "Balance" to "Баланс",
        "Band Assisted Pull Up" to "Подтягивание с эспандером",
        "Barbell Curl" to "Сгибание рук со штангой",
        "Barbell Row" to "Тяга штанги в наклоне",
        "Bench Press" to "Жим штанги лежа",
        "Beyond" to "Сверхпредельный",
        "Biceps" to "Бицепс",
        "Biceps Curl" to "Сгибание рук на бицепс",
        "Bulgarian Split Squat" to "Болгарские выпады",
        "Cable Curl" to "Сгибание рук на нижнем блоке",
        "Calf Raise" to "Подъем на носки",
        "Calves" to "Икры",
        "Celestial" to "Небесный",
        "Challenger" to "Претендент",
        "Chest" to "Грудь",
        "Chest, shoulders and triceps have the oldest recent work." to "Грудь, плечи и трицепс дольше всего не были в работе.",
        "Colossus" to "Колосс",
        "Conqueror" to "Завоеватель",
        "Cosmic Warlord" to "Космический воевода",
        "Deadlift" to "Становая тяга",
        "Dips" to "Отжимания на брусьях",
        "Dominator" to "Доминатор",
        "Driven" to "Мотивированный",
        "Dumbbell Bench Press" to "Жим гантелей лежа",
        "Elite" to "Элита",
        "Empyrean" to "Эмпирей",
        "Eternal" to "Вечный",
        "Exercise spotlight" to "Фокус упражнения",
        "Face Pull" to "Тяга каната к лицу",
        "Finish 100 total sets." to "Выполни в общей сложности 100 подходов.",
        "First session" to "Первая сессия",
        "First session in range" to "Первая сессия в выбранном периоде",
        "Flat vs previous" to "Без изменений от предыдущей",
        "Forearms" to "Предплечье",
        "French Press" to "Французский жим",
        "Galactic" to "Галактический",
        "Glutes" to "Ягодицы",
        "Hammer Curl" to "Молоточные сгибания рук",
        "Hamstrings" to "Бицепс бедра",
        "Hanging Leg Raise" to "Подъем ног в висе",
        "Hip Adduction" to "Сведение ног в тренажере",
        "Hip Thrust" to "Ягодичный мост со штангой",
        "Hold a 7-day streak." to "Удержи серию 7 дней.",
        "Holding steady" to "Стабильно",
        "Hyperextension" to "Гиперекстензия",
        "Immortal" to "Бессмертный",
        "In progress" to "В процессе",
        "Incline Bench Press" to "Жим штанги на наклонной скамье",
        "Incline Dumbbell Press" to "Жим гантелей на наклонной скамье",
        "Infinite" to "Бесконечный",
        "Ironclad" to "Несокрушимый",
        "Lat Pulldown" to "Тяга верхнего блока",
        "Lateral Raise" to "Подъемы гантелей через стороны",
        "Latest max" to "Последний макс",
        "Latest volume" to "Последний объем",
        "Lats" to "Широчайшие",
        "Leg Extension" to "Разгибание ног в тренажере",
        "Leg Press" to "Жим ногами в тренажере",
        "Leg day" to "День ног",
        "Legend" to "Легенда",
        "Legs" to "Ноги",
        "Log a few workouts" to "Запиши несколько тренировок",
        "Log a workout to start your momentum." to "Запиши тренировку, чтобы запустить свой темп.",
        "Log your first workout." to "Запиши свою первую тренировку.",
        "Lower back" to "Поясница",
        "Lunge" to "Выпады",
        "Lying Leg Curl" to "Сгибание ног лежа",
        "Machine Chest Fly" to "Сведение рук в тренажёре",
        "Machine Lateral Raise" to "Подъемы рук через стороны в тренажере",
        "Month" to "Месяц",
        "Mythic" to "Мифический",
        "No exercise data yet" to "Еще нет данных упражнения",
        "Nova" to "Нова",
        "Obliques" to "Косые мышцы",
        "Omega" to "Омега",
        "Omni" to "Омни",
        "One more session keeps the streak alive." to "Еще одна сессия поможет сберечь серию.",
        "Overhead Dumbbell Triceps Extension" to "Разгибание гантели над головой",
        "Overlord" to "Властелин",
        "Paragon" to "Парагон",
        "Pick an exercise to see solo progress." to "Выбери упражнение, чтобы увидеть свой прогресс.",
        "Plank" to "Планка",
        "Plate Loaded Row" to "Горизонтальная тяга в рычажном тренажере",
        "Plate Twist" to "Повороты корпуса с диском",
        "Posterior chain is behind" to "Задняя линия отстает",
        "Preacher Curl" to "Сгибание рук на скамье Скотта",
        "Prime" to "Прайм",
        "Pull" to "Тяга",
        "Pull Up" to "Подтягивание",
        "Pull day" to "Тяговый день",
        "Push" to "Жим",
        "Push Up" to "Отжимания от пола",
        "Push day" to "Жимовой день",
        "Quad load is much higher than hamstrings, glutes and lower back combined." to "Нагрузка на квадрицепсы намного выше, чем на бицепс бедра, ягодицы и поясницу вместе.",
        "Quads" to "Квадрицепсы",
        "Quads, hamstrings, glutes and calves are next in the rotation." to "Квадрицепсы, бицепс бедра, ягодицы и икры следующие в очереди.",
        "Reach ten logged workouts." to "Набери 10 записанных тренировок.",
        "Rear Delt Fly" to "Обратные разведения в тренажере",
        "Recommendations need enough history to compare muscle groups." to "Рекомендациям нужна история, чтобы сравнивать группы мышц.",
        "Romanian Deadlift" to "Румынская тяга",
        "Rookie" to "Новичок",
        "Seated Cable Row" to "Горизонтальная тяга блока",
        "Seated Dumbbell Curl" to "Сгибание рук с гантелями сидя",
        "Seated Leg Curl" to "Сгибание ног сидя",
        "Set century" to "Сотня подходов",
        "Setup" to "Старт",
        "Shoulder Press" to "Жим над головой",
        "Shoulders" to "Плечи",
        "Side Hyperextension" to "Боковая гиперэкстензия",
        "Singularity" to "Сингулярность",
        "Sovereign" to "Суверен",
        "Squat" to "Приседания со штангой",
        "Starter" to "Начинающий",
        "Steady" to "Стабильный",
        "Straight Arm Pulldown" to "Тяга прямых рук на верхнем блоке",
        "Streak keeper" to "Хранитель серии",
        "Striker" to "Ударник",
        "Ten sessions" to "Десять сессий",
        "These groups have not had meaningful work for 8+ days." to "Эти группы не получали заметную нагрузку 8+ дней.",
        "This month" to "В этом месяце",
        "This week" to "На этой неделе",
        "Titan" to "Титан",
        "Today" to "Сегодня",
        "Transcendent" to "Трансцендентный",
        "Triceps" to "Трицепс",
        "Triceps Pushdown" to "Разгибание рук на блоке",
        "Unlocked" to "Открыто",
        "Upper back" to "Верхняя часть спины",
        "Upright Row" to "Тяга штанги к подбородку",
        "V-Bar Triceps Pushdown" to "Разгибание рук на блоке с V-рукояткой",
        "Vanguard" to "Авангард",
        "Volume builder" to "Покоритель объёма",
        "Warborn" to "Рождённый воином",
        "Warm Up" to "Разминка",
        "Week" to "Неделя",
        "Weighted Crunch" to "Скручивание с диском",
        "Weighted Side Bend" to "Боковые наклоны с отягощением",
        "days" to "дней",
        "kg" to "кг",
        "sets" to "подходов",
        "volume" to "объёма",
        "workout" to "тренировка",
        "workouts" to "тренировок",
    )

    private val dynamic = listOf(
        Regex("^Log sets for (.+) to unlock trends\\.$") to "Добавь подходы для \$1, чтобы открыть тренды.",
        Regex("^Long gap: (.+)$") to "Давно не было: \$1",
        Regex("^Next: (.+)$") to "Далее: \$1",
        Regex("^(\\d+) workout XP this month\\. Mission rewards are tracked separately\\.$") to "\$1 XP за тренировки в этом месяце. Награды миссий учитываются отдельно.",
        Regex("^(\\d+) XP earned this month\\.$") to "В этом месяце заработано \$1 XP.",
        Regex("^(\\d+) exercises today$") to "\$1 упражнений сегодня",
        Regex("^Log (\\d+) exercise entries today\\.$") to "Запиши \$1 упражнений сегодня.",
        Regex("^(\\d+)-set target$") to "Цель: \$1 подходов",
        Regex("^Reach (\\d+) total sets today\\.$") to "Выполни \$1 подходов сегодня.",
        Regex("^Volume target (.+)$") to "Цель объёма: \$1",
        Regex("^Reach (.+) total volume today\\.$") to "Набери объём \$1 сегодня.",
        Regex("^Best session (.+) volume$") to "Лучшая сессия: объём \$1",
        Regex("^Push one session to (.+) volume today\\.$") to "Доведи объём одной сессии до \$1 сегодня.",
        Regex("^Session breadth (\\d+)$") to "Упражнений в сессии: \$1",
        Regex("^Fit (\\d+) exercises into one session today\\.$") to "Выполни \$1 упражнений за одну сессию сегодня.",
        Regex("^Session sets (\\d+)$") to "Подходов в сессии: \$1",
        Regex("^Build one session to (\\d+) sets today\\.$") to "Выполни \$1 подходов за одну сессию сегодня.",
        Regex("^(\\d+)-workout week$") to "\$1 тренировок за неделю",
        Regex("^(\\d+)-workout month$") to "\$1 тренировок за месяц",
        Regex("^Complete (\\d+) workouts this week\\.$") to "Выполни \$1 тренировок за неделю.",
        Regex("^Complete (\\d+) workouts this month\\.$") to "Выполни \$1 тренировок за месяц.",
        Regex("^(\\d+) active days$") to "\$1 активных дней",
        Regex("^Train on (\\d+) separate days this week\\.$") to "Тренируйся в \$1 разные дни на этой неделе.",
        Regex("^Train on (\\d+) separate days this month\\.$") to "Тренируйся в \$1 разные дни в этом месяце.",
        Regex("^(\\d+)-set week$") to "\$1 подходов за неделю",
        Regex("^(\\d+)-set month$") to "\$1 подходов за месяц",
        Regex("^Reach (.+) sets this week\\.$") to "Выполни \$1 подходов за неделю.",
        Regex("^Reach (.+) sets this month\\.$") to "Выполни \$1 подходов за месяц.",
        Regex("^(Weekly|Monthly) volume (.+)$") to "Объём за период: \$2",
        Regex("^Reach (.+) total volume this week\\.$") to "Набери объём \$1 за неделю.",
        Regex("^Reach (.+) total volume this month\\.$") to "Набери объём \$1 за месяц.",
        Regex("^(\\d+) exercises this week$") to "\$1 упражнений за неделю",
        Regex("^(\\d+) exercises this month$") to "\$1 упражнений за месяц",
        Regex("^Log (\\d+) exercise entries this week\\.$") to "Запиши \$1 упражнений за неделю.",
        Regex("^Log (\\d+) exercise entries this month\\.$") to "Запиши \$1 упражнений за месяц.",
        Regex("^(High-output days|Volume days|Strong sessions|Wide sessions) (\\d+)$") to "Количество: \$2",
        Regex("^Best session (.+) (sets|exercises)$") to "Лучшая сессия: \$1 \$2",
        Regex("^Build one session to (\\d+) sets this month\\.$") to "Выполни \$1 подходов за одну сессию в этом месяце.",
        Regex("^Fit (\\d+) exercises into one session this month\\.$") to "Выполни \$1 упражнений за одну сессию в этом месяце."
    )

    fun translate(english: String): String {
        exact[english]?.let { return it }
        dynamic.forEach { (pattern, replacement) ->
            if (pattern.matches(english)) return pattern.replace(english, replacement)
        }
        return english
    }
}
