"use strict";

const RUSSIAN_TEXT = new Map([
  ["2 / week", "2/неделя"],
  ["3 / week", "3/неделя"],
  ["4 / week", "4/неделя"],
  ["5 / week", "5/неделя"],
  ["6 / week", "6/неделя"],
  ["A fresh streak has started.", "Новая серия началась."],
  ["A legacy storage-key collision was detected. Sign-in is blocked so one local account cannot open another account's data.", "Выявлена ​​коллизия старого ключа хранилища. Вход заблокирован, чтобы один локальный аккаунт не открыл данные другого."],
  ["A one-time Garmin token will be shown. It works like a password: paste it only into this watch's Connect IQ settings. GymApp will not store or show it again. Continue?", "Будет показан одноразовый токен Garmin. Он работает как пароль: вставь его только в настройку Connect IQ этих часов. GymApp не будет сохранять и не покажет его снова. Продолжить?"],
  ["A previous Garmin device creation is still awaiting revocation. Keep this page open and retry before pairing again.", "Предварительное создание устройства Garmin еще ожидает отзыв. Не закрывай эту страницу и повтори попытку перед новым сообщением."],
  ["A previous Garmin queue result is still unknown. Start a different logical submission anyway? It may create a second plan if the earlier request succeeded. Cancel is recommended.", "Результат предыдущего Garmin-запроса еще неизвестен. Все равно начать другую отправку? Если предыдущий запрос сработал, может появиться второй план. Рекомендуется отменить."],
  ["A redacted diagnostics report is not a restorable backup.", "Обезличенный отчет диагностики не является резервной копией."],
  ["Account", "Аккаунт"],
  ["Account created. Check your email to confirm the account, then log in.", "Account created. Нажмите ваш e-mail, чтобы подтвердить свой аккаунт."],
  ["Account name is too long.", "Название аккаунта слишком длинное."],
  ["Account switch was cancelled.", "Переключение аккаунта отменено."],
  ["Accumulate 10000 total volume.", "Набери общий объём 10 000."],
  ["Achievements", "Достижение"],
  ["Active daily, weekly, and monthly missions rotate from a huge challenge pool.", "Активные ежедневные, недельные и месячные миссии выбираются из пула вызовов."],
  ["Activity Heatmap", "Карта активности"],
  ["Add Exercise", "Добавить упражнение"],
  ["Add Exercise to This Workout", "Add Exercise to This Workout"],
  ["Add Set", "Добавить подход"],
  ["Add Workout", "Добавить тренировку"],
  ["Add a custom movement or open a saved exercise to view its history.", "Добавь собственное упражнение или открой сохраненное, чтобы просмотреть историю."],
  ["Add exercise", "Добавить упражнение"],
  ["Add sets to see chart.", "Добавь подходы, чтобы увидеть график."],
  ["Add to Workout", "Add to Workout"],
  ["Add workouts to unlock daily, weekly, and monthly goals.", "Добавь тренировки, чтобы открыть ежедневные, недельные и лунные цели."],
  ["Add your first workout to unlock smarter recommendations.", "Добавь первую тренировку, чтобы открыть более умные рекомендации."],
  ["Aesthetic Cut", "Сушка"],
  ["Aesthetic goal: the plan favors clean volume and technique.", "Цель сушки: план содержит чистый объем и технику."],
  ["All", "Все"],
  ["All muscles", "Все мышцы"],
  ["All saved exercises are already in this workout.", "Все хранящиеся упражнения являются обязательными в этой работе."],
  ["All time", "За все время"],
  ["All-time best", "Лучшее за все время"],
  ["An account with this email already exists. Log in or resend the confirmation email.", "Примерно с этим электронной почтой или существующими. Найти или продлить электронную почту."],
  ["An exercise or its set list is invalid.", "Упражнение или список его подходов некорректны."],
  ["An exercise with this name already exists.", "Упражнение с таким названием уже существует."],
  ["An incomplete Garmin pairing could not be revoked. Cancel to keep this cloud session and retry (recommended). Choose OK only to sign out locally; GymApp will retry cleanup after you sign back into this account.", "Не удалось отозвать незавершенное сообщение Garmin. Нажмите «Отмена», чтобы сохранить облачную сессию и повторить попытку (рекомендуется). Нажмите OK только для локального выхода; GymApp повторит очистку после входа в этот аккаунт."],
  ["Anonymous", "Без имени"],
  ["Apex", "Апекс"],
  ["Apply Smart Plan", "Применить план"],
  ["Ascendant", "Вознесенный"],
  ["Assisted Pull Up", "Подтягивание в гравитроне"],
  ["Auto mapping", "Автомапинг"],
  ["Auto mapping works first, manual choices override it.", "Автомапинг работает базово, ручной выбор перекрывает его."],
  ["Average Max", "Средний максимум"],
  ["Average volume", "Средний объем"],
  ["Avg / Set", "Сер. / подход"],
  ["Avg HR", "Avg HR"],
  ["Back", "Позади"],
  ["Back to workouts", "Обратно к тренировкам"],
  ["Backup JSON ready", "JSON бекапа готов"],
  ["Backup and diagnostics", "Резервное копирование и диагностика"],
  ["Backup imported.", "Бекап импортирован."],
  ["Backups merge into the current profile and skip duplicate sessions.", "Резервные копии объединяются с текущим профилем и пропускают дубликаты тренировок."],
  ["Balanced", "Баланс"],
  ["Band Assisted Pull Up", "Подтягивание с эспандером"],
  ["Barbell Curl", "Сгибание рук со штангой"],
  ["Barbell Row", "Тяга штанги в наклоне"],
  ["Barbell Squat", "Присед со штангой"],
  ["Based on muscle load and recent training gaps.", "На основе погрузки мышц и последних пауз в тренировках."],
  ["Bench Press", "Жим штанги лежа"],
  ["Best", "Лучшее"],
  ["Best Weight", "Лучший вес"],
  ["Beyond", "Сверхпредельный"],
  ["Biceps Curl", "Сгибание рук на бицепс"],
  ["Bring up", "Подтяни"],
  ["Build plan: hold weight and add reps before the next jump.", "План набора: держи вес и добавь повторы перед следующим прыжком."],
  ["Build today's session", "Собери сегодняшнюю тренировку"],
  ["Built-in", "Встроенная"],
  ["Bulgarian Split Squat", "Болгарские выпады"],
  ["By name", "Под названием"],
  ["Cable Curl", "Сгибание рук на нижнем блоке"],
  ["Calf Raise", "Подъем на носки"],
  ["Calorie deficit: progression is more conservative to protect recovery.", "Дефицит калорий: прогрессия более осторожна для восстановления."],
  ["Calorie mode", "Режим калорий"],
  ["Celestial", "Небесный"],
  ["Challenger", "Претендент"],
  ["Check your sets, then save to move straight into workout details.", "Проверь подходы и сохрани, чтобы перейти к деталям тренировки."],
  ["Choose muscles for this exercise.", "Выбери мышцы для этого упражнения."],
  ["Clear search", "Очистить поиск"],
  ["Clipboard access is unavailable.", "Доступ к буферу обмена недоступен."],
  ["Clipboard write failed.", "Невозможно записать в буфер обмена."],
  ["Close dialog", "Закрыть диалог"],
  ["Cloud", "Облако"],
  ["Cloud account", "Облачный аккаунт"],
  ["Cloud data recovery", "Восстановление облачных данных"],
  ["Cloud login complete.", "Cloud login complete."],
  ["Cloud login complete. Recovery action is required before sync.", "Облачный вход выполнен. Перед синхронизацией требуется возобновление."],
  ["Cloud login is not configured.", "Cloud login не является configured."],
  ["Cloud login is ready after Supabase keys are added.", "Облачный вход заработает после добавления ключей Supabase."],
  ["Cloud rating is disabled until Supabase is configured.", "Облачный рейтинг выключен, пока Supabase не настроен."],
  ["Cloud recovery failed.", "Не удалось восстановить облачные данные."],
  ["Cloud recovery session is stale. Sign out and log in again.", "Сессия облачного обновления устарела. Выйди и войди снова."],
  ["Cloud request failed. Check your connection and try again.", "Cloud request failed. Выполните ваше сопряжение и попытайтесь."],
  ["Cloud state recovery completed.", "Восстановление облачного состояния завершено."],
  ["Cloud state was recovered, but the public profile refresh should be retried later.", "Облачное состояние восстановлено, но обновления публичного профиля следует повторить позже."],
  ["Cloud sync conflicted. Reload before saving again.", "Облачные перемены конфликтуют. Обновленные данные перед повторной сохранностью."],
  ["Cloud sync failed.", "Синхронизация не удалась."],
  ["Colors show which muscle groups carried the most load.", "Цвета показывают, какие группы мышц получили наибольшую нагрузку."],
  ["Colossus", "Колосс"],
  ["Comeback plan: restart below the last weight after a training gap.", "План возврата: начни ниже последнего веса после паузы."],
  ["Common", "Обычная"],
  ["Completed", "Выполнено"],
  ["Completed missions and new badges from this finish.", "Завершены миссии и новые бейджи после финиша."],
  ["Confidence", "Уверенность"],
  ["Confirm your email first, then log in.", "Пожалуйста, напишите ваш электронной почте в первый раз."],
  ["Confirmation email sent. Check your inbox and spam folder.", "Confirmation email sent. Check your inbox and spam folder."],
  ["Conqueror", "Завоеватель"],
  ["Consistency", "Стабильность"],
  ["Consistency milestone reached.", "Достигнут вех стабильности."],
  ["Copy JSON", "Копировать JSON"],
  ["Copy Last +2.5 kg", "Копировать +2.5 кг"],
  ["Copy Last Set", "Копировать подход"],
  ["Copy Previous Workout", "Скопировать день"],
  ["Copy a previous workout", "Скопировать предыдущее"],
  ["Copy this Garmin pairing token into Connect IQ settings now. Treat it as a password. It will not be stored or shown again. Choose Cancel to revoke it.", "Скопируйте этот токен Garmin в настройку Connect IQ сейчас. Относись к нему как к паролю. Он не будет храниться и больше не показываться. Нажмите «Отмена», чтобы отозвать его."],
  ["Core", "Кор"],
  ["Cosmic Warlord", "Космический воевода"],
  ["Could not load cloud rating. Try refresh again.", "Не удалось загрузить облачный рейтинг. Попробуй обновить снова."],
  ["Create account", "Создать аккаунт"],
  ["Current", "Текущий"],
  ["Current level", "Текущий уровень"],
  ["Current title", "Текущий ранг"],
  ["Custom", "Собственный"],
  ["Daily", "Ежедневные"],
  ["Daily Missions", "Ежедневные миссии"],
  ["Daily consistency goals reset at midnight.", "Ежедневные цели стабильности обновляются в полночь."],
  ["Deadlift", "Становая тяга"],
  ["Deficit", "Дефицит"],
  ["Delete exercise", "Удалить упражнение"],
  ["Delete workout", "Delete workout"],
  ["Deload", "Делоад"],
  ["Dialog", "Диалог"],
  ["Dips", "Отжимания на брусьях"],
  ["Display name", "Имя в рейтинге"],
  ["Display name can use letters, numbers, spaces, dot, dash and underscore.", "Display name может использовать листы, номера, пространства, dot, dash and underscore."],
  ["Dominator", "Доминатор"],
  ["Download", "Загрузить"],
  ["Download original private JSON", "Загрузить оригинальный частный JSON"],
  ["Driven", "Мотивированный"],
  ["Dumbbell Bench Press", "Жим гантелей лежа"],
  ["Duration", "Duration"],
  ["Earn XP to unlock rank titles.", "Зарабатывай XP, чтобы открывать ранги."],
  ["Edit Set", "Редактировать подход"],
  ["Elite", "Элита"],
  ["Email", "Email"],
  ["Email does not match.", "Email не match."],
  ["Email or password is incorrect.", "Email или password is incorrect."],
  ["Empyrean", "Эмпирей"],
  ["Enter", "Войти"],
  ["Enter a valid email address.", "Введите правильный адрес электронной почты."],
  ["Enter a valid weight and whole-number reps for every set.", "Введи корректный вес и целое количество повторов для каждого подхода."],
  ["Enter account name.", "Введи название аккаунта."],
  ["Enter exercise name.", "Введи название упражнения."],
  ["Enter valid reps and optional weight.", "Введи корректные повторы и вес."],
  ["Enter your email.", "Введите свой e-mail."],
  ["Eternal", "Вечный"],
  ["Exercise", "Упражнение"],
  ["Exercise Rest", "Отдых"],
  ["Exercise library", "Каталог упражнений"],
  ["Exercise mapping", "Маппинг упражнений"],
  ["Exercise name", "Название упражнения"],
  ["Exercise name is too long.", "Название упражнения слишком длинное."],
  ["Exercises", "Упражнения"],
  ["Exercises for", "Упражнения для"],
  ["Existing Garmin recovery was cancelled. No new device identity was created.", "Восстановление существующего Garmin отменено. Новый идентификатор устройства не создан."],
  ["Export JSON", "Экспорт JSON"],
  ["Export redacted diagnostics", "Экспорт обезличенной диагностики"],
  ["Face Pull", "Тяга каната к лицу"],
  ["Fallback for this browser only.", "Запасной режим только для этого браузера."],
  ["Finish 100 total sets.", "Выполни в общей сложности 100 подходов."],
  ["Finish Workout", "Завершить"],
  ["Finish the pending Garmin recovery? This rotates a replacement token for the same watch identity and shows it once. Cancel leaves the current server token unchanged.", "Завершить неоконченное восстановление Garmin? Будет создан новый токен для того же идентификатора часов и показан один раз. \"Отменить\" не изменит действующий серверный токен."],
  ["First download the untouched private JSON for offline recovery. Replacing it with an empty valid state is permanent and uses the exact server revision so another device's newer update cannot be overwritten.", "Сначала загрузил неизмененный приватный JSON для офлайн-восстановления. Замена на пустое корректное состояние необратима и использует точную ревизию сервера, поэтому новые изменения с другого устройства не будут перезаписаны."],
  ["First logged best", "Первый зафиксированный рекорд"],
  ["First session", "Первая сессия"],
  ["First tracked session", "Первая отслеженная тренировка"],
  ["French Press", "Французский жим"],
  ["Front", "Впереди"],
  ["Full Body", "Все тело"],
  ["Galactic", "Галактический"],
  ["Garmin kcal", "Garmin kcal"],
  ["Garmin pairing revoked. Reset the watch app before creating a new pairing.", "Сообщение Garmin отозвано. Сбрось приложение на часах перед созданием нового сообщения."],
  ["Garmin pairing was cancelled.", "Сообщение Garmin отменено."],
  ["Garmin strength metrics", "Garmin strength metrics"],
  ["Garmin strength workout", "Garmin strength workout"],
  ["Garmin sync is already in progress.", "Синхронизация Garmin уже производится."],
  ["Garmin sync is already running in another GymApp tab. Finish it there before retrying.", "Синхронизация Garmin уже производится в другой вкладке GymApp. Завершите ее там перед повторной попыткой."],
  ["Garmin token rotated for the existing watch. Save it in Connect IQ settings, then sync on the watch.", "Токен Garmin обновлен для имеющихся часов. Сохрани его в настройках Connect IQ и запусти синхронизацию на часах."],
  ["Garmin token rotation completed for a stale account session. Sign back into the same account and run Sync Watch to finish recovery for this watch identity.", "Ротация токена Garmin завершена для устаревшей сессии. Войди в тот же аккаунт и запусти Sync Watch, чтобы завершить восстановление этих часов."],
  ["Garmin token shown once. After saving it in Connect IQ settings, sync on the watch.", "Токен Garmin показан один раз. Сохрани его в настройках Connect IQ и запусти синхронизацию на часах."],
  ["Garmin unpair failed.", "Garmin не удалось отключить."],
  ["Generate Smart Workout", "Сгенерировать тренировки"],
  ["Gym kcal", "Gym kcal"],
  ["Gym kcal is saved from the Garmin app strength formula. Garmin kcal is the system value Garmin Connect uses for daily calories.", "Gym kcal находится в Garmin app strength formula. Garmin kcal является системным значением Garmin Connect используется для дневных calories."],
  ["GymApp links", "Ссылки GymApp"],
  ["Hammer Curl", "Молоточные сгибания рук"],
  ["Hanging Leg Raise", "Подъем ног в висе"],
  ["High", "Высокий"],
  ["Hip Adduction", "Сведение ног в тренажере"],
  ["Hip Thrust", "Ягодичный мост со штангой"],
  ["History", "История"],
  ["Hold a 7-day streak.", "Удержи серию 7 дней."],
  ["Holding steady", "Стабильно"],
  ["Hyperextension", "Гиперекстензия"],
  ["Immortal", "Бессмертный"],
  ["Import", "Импорт"],
  ["Import JSON", "Импорт JSON"],
  ["Import backup", "Импорт бекапа"],
  ["In progress", "В процессе"],
  ["Incline Bench Press", "Жим штанги на наклонной скамье"],
  ["Incline Dumbbell Press", "Жим гантелей на наклонной скамье"],
  ["Infinite", "Бесконечный"],
  ["Invalid backup.", "Некорректный бекап."],
  ["Ironclad", "Несокрушимый"],
  ["JSON copied.", "JSON скопирован."],
  ["Keep logging to unlock more.", "Продолжай записывать тренировки, чтобы открыть больше."],
  ["LEVEL", "УРОВЕНЬ"],
  ["Last", "Последняя"],
  ["Last session was stable across the sets.", "Последняя сессия была стабильна по подходам."],
  ["Lat Pulldown", "Тяга верхнего блока"],
  ["Lateral Raise", "Подъемы гантелей через стороны"],
  ["Latest max", "Последний макс"],
  ["Latest volume", "Последний объем"],
  ["Leaderboard", "Таблица рейтинга"],
  ["Least frequent", "Самые редкие"],
  ["Leg Extension", "Разгибание ног в тренажере"],
  ["Leg Press", "Жим ногами в тренажере"],
  ["Leg day", "День ног"],
  ["Legend", "Легенда"],
  ["Less", "Меньше"],
  ["Level", "Уровень"],
  ["Level progress", "Прогресс уровня"],
  ["Load", "Погрузка"],
  ["Loading", "Загрузка"],
  ["Loading the latest cloud standings.", "Загружаем последний облачный рейтинг."],
  ["Local", "Локальный"],
  ["Local account could not be saved.", "Не удалось сохранить локальный аккаунт."],
  ["Local account limit reached.", "Достигнут предел локальных аккаунтов."],
  ["Local mode. Sign in to a cloud account to join the rating.", "Местный режим. Войди в облачный аккаунт, чтобы присоединиться к рейтингу."],
  ["Locked", "Закрыто"],
  ["Log in", "Войти"],
  ["Log in instead", "Войти вместо"],
  ["Log in to cloud first.", "Найти в cloud first."],
  ["Log sets to light up the body map.", "Запиши подходы для подсветки карты тела."],
  ["Log your first workout.", "Запиши свою первую тренировку."],
  ["Log your plan fast and keep momentum with smart set shortcuts.", "Быстро запиши план и держи темп разумными действиями для подходов."],
  ["Logged", "Logged"],
  ["Logged today", "Записано сегодня"],
  ["Lower body", "Низ тела"],
  ["Lunge", "Выпады"],
  ["Lying Leg Curl", "Сгибание ног лежа"],
  ["Machine Chest Fly", "Сведение рук в тренажёре"],
  ["Machine Lateral Raise", "Подъемы рук через стороны в тренажере"],
  ["Maintenance", "Поддержка"],
  ["Manage your library, history, muscle groups, and backups.", "Управляй каталогом, историей, группами мышц и резервными копиями."],
  ["Map", "Маппинг"],
  ["Mapped", "Сопоставлено"],
  ["Mapped muscle load will appear after sets are saved.", "Погрузка мышц появится после сохранения подходов."],
  ["Max HR", "Max HR"],
  ["Maximum weight", "Максимальный вес"],
  ["Maximum weight and session volume over time.", "Максимальный вес и объем тренировки по времени."],
  ["Mission", "Миссия"],
  ["Mission XP from completed goals", "XP миссий за выполненные цели"],
  ["Missions", "Миссии"],
  ["Momentum", "Импульс"],
  ["Month", "Месяц"],
  ["Month XP", "XP за месяц"],
  ["Monthly", "Лунные"],
  ["Monthly Missions", "Месячные миссии"],
  ["Monthly Snapshot", "Итог месяца"],
  ["Monthly goals measure the whole calendar month.", "Месячные цели считают весь календарный месяц."],
  ["More", "Больше"],
  ["Most frequent", "Самые частые"],
  ["Most loaded today", "Больше всего нагружено сегодня"],
  ["Muscle Gain", "Набор мышц"],
  ["Muscle Map", "Карта мышц"],
  ["Muscle groups", "Группы мышц"],
  ["Muscle load map", "Карта погрузки мышц"],
  ["Mythic", "Мифический"],
  ["Name", "Имя"],
  ["Name in English or Ukrainian", "Название на украинском или английском"],
  ["New", "Новое"],
  ["New PR", "New PR"],
  ["New sessions will appear here as soon as you log them.", "Новые тренировки появятся сразу после сохранения."],
  ["Next", "Дали"],
  ["Next suggested workout", "Следующая рекомендованная тренировка"],
  ["Next suggested workout: legs", "Следующая рекомендуемая тренировка: ноги"],
  ["Next suggested workout: pull", "Следующая рекомендованная тренировка: pull"],
  ["Next suggested workout: push", "Следующая рекомендованная тренировка: push"],
  ["Next title", "Следующий ранг"],
  ["No active Garmin pairing is available.", "Активное сообщение Garmin отсутствует."],
  ["No cloud recovery data is available.", "Данные для облачного обновления недоступны."],
  ["No data", "Нет данных"],
  ["No exercise data yet", "Еще нет данных упражнения"],
  ["No exercises yet.", "Упражнений еще нет."],
  ["No history for this exercise yet.", "Истории для этого упражнения еще нет."],
  ["No history in this month.", "Нет истории за этот месяц."],
  ["No leaderboard rows yet.", "Строков рейтинга еще нет."],
  ["No logged exercises for this muscle in the selected period.", "В выбранном периоде этой группы еще нет упражнений."],
  ["No matching exercises.", "Упражнения по этим фильтрам не найдены."],
  ["No missions yet", "Миссий еще нет"],
  ["No new unlocks", "Новых открытий нет"],
  ["No note", "No note"],
  ["No previous workouts yet.", "Предыдущих тренировок еще нет."],
  ["No ranks yet", "Рангов еще нет"],
  ["No saved history yet, so this starts with a clean baseline.", "Истории нет, поэтому план начинается с чистой базы."],
  ["No set data", "No set data"],
  ["No sets", "No sets"],
  ["No sets were imported for this exercise.", "Не все были imported for this exercise."],
  ["No workouts in this month.", "Нет тренировок в этом месяце."],
  ["Not mapped", "Не сопоставлено"],
  ["Note", "Заметка"],
  ["Nova", "Нова"],
  ["Offline local account", "Оффлайн-аккаунт"],
  ["Omega", "Омега"],
  ["Omni", "Омни"],
  ["One exercise exceeds the set limit.", "Одно упражнение превышает предел подходов."],
  ["Open", "Открыто"],
  ["Open in Garmin Connect IQ", "Открыть в Garmin Connect IQ"],
  ["Open the full rank list and check the next unlocks.", "Открой полный список рангов и проверьте следующие открытия."],
  ["Overhead Dumbbell Triceps Extension", "Разгибание гантели над головой"],
  ["Overlord", "Властелин"],
  ["Overview", "Обзор"],
  ["Paragon", "Парагон"],
  ["Password", "Пароль"],
  ["Password must be 8+ characters and include letters and numbers.", "Пароль должен содержать не менее 8 символов, букв и цифр."],
  ["Password must be 8-72 characters and include letters and numbers.", "Password должны быть 8-72 characters and include letters and numbers."],
  ["Passwords do not match.", "Пароли не совпадают."],
  ["Paste Supabase keys into supabase-config.js to enable real network login.", "Вставьте ключи Supabase в supabase-config.js, чтобы включить подлинный сетевой вход."],
  ["Paste exported GymApp JSON here", "Встав сюда экспортированный JSON GymApp"],
  ["Paste this replacement token into the same watch's Connect IQ settings now. The old token has stopped working. This token will not be stored or shown again.", "Встал этот новый токен в настройку Connect IQ тех же часов. Старый токен уже не работает. Новый токен не будет храниться и больше не показываться."],
  ["Peak weight", "Пиковый вес"],
  ["Pending Garmin recovery was not changed.", "Незавершенное обновление Garmin не изменено."],
  ["Permanently replace the quarantined cloud row with an empty GymApp state? Download the original JSON first if you may need its private workout history. Cancel is the safe default.", "Необратимо заменить карантинную облачную запись пустым состоянием GymApp? Сначала загрузи оригинальный JSON, если может потребоваться частная история тренировок. «Отмена» — безопасный выбор по умолчанию."],
  ["Permanently revoke this Garmin pairing? Cloud sync on the current watch will stop. Before pairing it again, reset or reinstall GymApp on the watch so it forgets the old device identity. Cancel keeps the working pairing.", "Навсегда отзывать это сообщение Garmin? Облачная синхронизация на текущих часах прекратится. Перед повторным соединением скинов или переустановки GymApp на часах, чтобы они забыли старый идентификатор устройства. «Отменить» сохранит рабочее сообщение."],
  ["Personal record", "Личный рекорд"],
  ["Personal records", "Личные рекорды"],
  ["Pick an exercise to see solo progress.", "Выбери упражнение, чтобы увидеть свой прогресс."],
  ["Plan queued for Garmin. Open the watch app and run Cloud sync.", "План нуждается в Garmin. Open the watch app and run Cloud sync."],
  ["Plan templates", "Шаблоны плана"],
  ["Plank", "Планка"],
  ["Plate Loaded Row", "Горизонтальная тяга в рычажном тренажере"],
  ["Plate Twist", "Повороты корпуса с диском"],
  ["Plateau plan: change the rep target to break the flat trend.", "План плато: изменить цель повторов, чтобы сдвинуть прогресс."],
  ["Please fill every selected set within the workout limits.", "Заполни все выбранные подходы в пределах тренировочных лимитов."],
  ["Please fill exercises and sets first.", "Please fill exercises and sets first."],
  ["Preacher Curl", "Сгибание рук на скамье Скотта"],
  ["Previous best", "Предыдущий рекорд"],
  ["Prime", "Прайм"],
  ["Privacy", "Конфиденциальность"],
  ["Progress", "Прогресс"],
  ["Progress Summary", "Итог прогресса"],
  ["Progress, goals, achievements", "Прогресс, цели, достижения"],
  ["Progression plan: small load increase with controlled reps.", "План прогрессии: небольшое увеличение веса с контролируемыми повторами."],
  ["Pull Up", "Подтягивание"],
  ["Pull day", "Тяговый день"],
  ["Push Pull Legs", "Push Pull Legs"],
  ["Push Up", "Отжимания от пола"],
  ["Push day", "Жимовой день"],
  ["Push day, pull day, deload...", "Push день, pull день, делoad..."],
  ["Rank Titles", "Ранги"],
  ["Rank ladder", "Лестница рангов"],
  ["Rare", "Редкая"],
  ["Rating", "Рейтинг"],
  ["Reach ten logged workouts.", "Набери 10 записанных тренировок."],
  ["Ready", "Готово"],
  ["Rear Delt Fly", "Обратные разведения в тренажере"],
  ["Recent reps or volume dipped, so the plan stays conservative.", "Повторы или объем просели, поэтому план осторожен."],
  ["Recent unlocks and the next solo milestones.", "Последние открытия и следующие личные вехи."],
  ["Recent volume dropped compared with the previous session.", "Последний объем ниже предыдущей сессии."],
  ["Recent volume is trending up.", "Последний объем растет."],
  ["Recommendations", "Рекомендации"],
  ["Recovery JSON download failed.", "Не удалось загрузить JSON для восстановления."],
  ["Recovery plan: reduce load because the last result looked strained.", "План восстановления: снизу нагрузки, потому что последний результат был тяжелым."],
  ["Redacted diagnostics ready", "Обезличенная диагностика готова"],
  ["Refresh", "Обновить"],
  ["Remove exercise", "Убрать упражнение"],
  ["Remove set", "Удалить подход"],
  ["Rename Exercise", "Переименовать"],
  ["Rename exercise", "Переименовать упражнение"],
  ["Repeat Last Workout", "Повторить последнее"],
  ["Repeat email", "Повтори email"],
  ["Repeat password", "Повтори пароль"],
  ["Replace cloud data with empty state", "Заменить облачные данные пустым состоянием"],
  ["Reps", "Повторения"],
  ["Required level", "Нужный уровень"],
  ["Required total XP", "Требуется XP"],
  ["Resend confirmation email", "Отправить еще раз подтверждение"],
  ["Rewards", "Награды"],
  ["Romanian Deadlift", "Румынская тяга"],
  ["Rookie", "Новичок"],
  ["Save", "Сохранить"],
  ["Save Workout", "Сохранить тренировку"],
  ["Saved accounts", "Сохраненные аккаунты"],
  ["Search exercises", "Поиск упражнений"],
  ["Seated Cable Row", "Горизонтальная тяга блока"],
  ["Seated Dumbbell Curl", "Сгибание рук с гантелями сидя"],
  ["Seated Leg Curl", "Сгибание ног сидя"],
  ["Secure cross-tab Garmin sync is unavailable in this browser. Close other GymApp tabs and use a supported browser before retrying.", "Безопасная синхронизация Garmin между вкладками в этом браузере недоступна. Закрой другие вкладки GymApp и повтори в поддерживаемом браузере."],
  ["Secure local account creation is unavailable in this browser.", "Безопасное создание локального аккаунта недоступно в этом браузере."],
  ["See every title, its level gate, and the XP needed to unlock it.", "Просмотри все ранги, нужный уровень и XP для открытия."],
  ["Select exercise", "Выбери упражнение"],
  ["Session volume", "Объем тренировки"],
  ["Sessions", "Сессии"],
  ["Set", "Подход"],
  ["Set century", "Сотня подходов"],
  ["Set deleted.", "Подход удален."],
  ["Sets", "Подходы"],
  ["Several sessions stayed near the same top weight.", "Несколько сессий держались у того же максимального веса."],
  ["Share PDF report", "PDF отчет"],
  ["Shoulder Press", "Жим над головой"],
  ["Showing local stats while the cloud rating is unavailable.", "Показываем локальные данные, пока облачный рейтинг недоступен."],
  ["Side Hyperextension", "Боковая гиперэкстензия"],
  ["Sign in to sync workouts across devices.", "Вход для синхронизации тренировки между устройствами."],
  ["Sign out without changes", "Выйти без изменений"],
  ["Sign-out was cancelled so Garmin revocation can be retried.", "Выход отменен, чтобы можно было повторить отзыв Garmin."],
  ["Sign-out was stopped because browser account data could not be erased. The account remains open in this tab. Restore storage access and retry.", "Выход остановлен, так как не удалось удалить данные аккаунта в браузере. Аккаунт остается открытым в этой вкладке. Восстанови доступ к хранилищу и повтори попытку."],
  ["Signed out locally, but server revocation was not confirmed. That old session may remain valid until server expiry or administrative revocation.", "Локальный выход выполнен, но серверный отзыв не подтвержден. Старая сессия может действовать до завершения серверного срока или административного отзыва."],
  ["Signed out locally. An incomplete Garmin pairing still needs cleanup; sign back into the same account to retry.", "Локальный выход выполнен. Незавершенное сообщение Garmin еще нуждается в очищении; войди снова в этот аккаунт, чтобы повторить."],
  ["Singularity", "Сингулярность"],
  ["Smart Coach", "Умный коуч"],
  ["Smart Coach uses this to match your plan, goal and recovery.", "Умный коуч использует это, чтобы подобрать план, цель и восстановление."],
  ["Smart workout generated", "Умная тренировка сгенерирована"],
  ["Solo Progress", "Соло прогресс"],
  ["Sovereign", "Суверен"],
  ["Squat", "Приседания со штангой"],
  ["Starter", "Начинающий"],
  ["Starter plan", "Стартовый план"],
  ["Starter plan: build clean reps and save the first baseline.", "Стартовый план: сделай чистые повторы и сохрани первую базу."],
  ["Steady", "Стабильный"],
  ["Stop", "Стоп"],
  ["Straight Arm Pulldown", "Тяга прямых рук на верхнем блоке"],
  ["Streak", "Серия"],
  ["Streak extended to", "Серия продлена до"],
  ["Streak keeper", "Хранитель серии"],
  ["Strength", "Сила"],
  ["Striker", "Ударник"],
  ["Suggested from your recent exercise pattern and training profile.", "Подобрано по последнему паттерну упражнений и профилю тренировок."],
  ["Supabase is not configured.", "Supabase не является configured."],
  ["Support", "Поддержка"],
  ["Surplus", "Профицит"],
  ["Switch", "Изменить"],
  ["Sync Plan to Watch", "Синхронизировать с часами"],
  ["Synced sets are grouped below. Expand an exercise to edit weight, reps, add a missed set, or delete a wrong one.", "Synced sets are grouped below. Распространение на регулировку гибели, reps, add mised set, або delete a wrong one."],
  ["Synced through Supabase.", "Синхронизирован через Supabase."],
  ["TOTAL XP", "ВСЕГО XP"],
  ["Tap a workout to open its details.", "Нажмите на тренировку, чтобы открыть детали."],
  ["Target muscles", "Целевые мышцы"],
  ["Ten sessions", "Десять сессий"],
  ["The Garmin binding could not be saved, so the unseen token was revoked. Free browser storage and try again.", "Не удалось сохранить привязку Garmin, поэтому непоказанный токен отозван. Освободи место в хранилище браузера и попробуй еще раз."],
  ["The Garmin token could not be revoked. Use Unpair Garmin to retry revocation, or run Sync Watch again to rotate a replacement token for the same watch identity.", "Не удалось отозвать токен Garmin. Воспользуйся «Отключить Garmin», чтобы повторить отзыв, или снова запусти Sync Watch для ротации нового токена тех же часов."],
  ["The exercise catalog has reached its limit.", "Каталог упражнений достиг лимита."],
  ["The increase is intentionally conservative.", "Увеличение специально осторожно."],
  ["The pending Garmin device is no longer active. Run Sync Watch again to choose or create a pairing.", "Незавершенное устройство Garmin больше не активно. Снова запусти Sync Watch, чтобы выбрать или создать соединение."],
  ["The previous Garmin request ID conflicted with server state. Start a new request ID for this submission? Cancel keeps the conflict for review.", "Предыдущий Garmin request ID конфликтует с состоянием сервера. Создать новый request ID для этой отправки? «Отменить» сохранит конфликт для проверки."],
  ["The replacement Garmin token was not confirmed. Run Sync Watch again to rotate another token for the same watch identity.", "Новый токен Garmin не подтвержден. Запусти Sync Watch еще раз, чтобы создать другой токен для того же идентификатора часов."],
  ["The report window was blocked.", "Окно отчета заблокировано."],
  ["The unseen Garmin token could not be persisted or revoked. Keep this page open and retry Garmin sync or sign-out to revoke it.", "Непоказанный токен Garmin не удалось ни сохранить, ни отозвать. Не закрывай эту страницу и повтори Garmin sync или выход, чтобы отозвать его."],
  ["This backup belongs to another account.", "Этот бекап принадлежит другому аккаунту."],
  ["This exercise has reached its set limit.", "Упражнение достигло лимита подходов."],
  ["This exercise has reached the set limit.", "Достигнут лимит подходов для упражнения."],
  ["This full backup contains private workout history and account metadata. Copy it to the system clipboard? Other apps may be able to read it.", "Полный бекап содержит приватную историю тренировок и данные аккаунта. Копировать его в системный буфер? Другие приложения могут иметь к нему доступ."],
  ["This imported workout contains exercise names, but no weights or reps. Export a full Backup JSON from the Android app and import it again.", "Это imported workout contains exercise names, но не weights or reps. Получить полный Backup JSON от Android приложения и импортировать его."],
  ["This is close to your best estimated strength for the exercise.", "Это близко к лучшей оценке силы в этом упражнении."],
  ["This legacy local account name is ambiguous. Its stored data was left untouched; rename/recover it before signing in.", "Это название старого локального аккаунта неоднозначно. Сохраненные данные не изменены; возобнови или переименуй аккаунт перед входом."],
  ["This muscle group is behind your current total load.", "Эта группа мышц отстает по текущей общей нагрузке."],
  ["This report will include the full private backup. Continue to the print dialog?", "Отчет будет содержать полный частный бекап. Продолжить диалог печати?"],
  ["This saved local account is missing its state. Nothing was created or merged automatically.", "У этого сохраненного локального аккаунта отсутствует состояние. Ничего не создано и не объединено автоматически."],
  ["This workout exceeds the supported size.", "Тренировка превышает допустимый размер."],
  ["This workout has reached its set limit.", "Тренировка достигла лимита подходов."],
  ["This workout has reached the exercise limit.", "Достигнут лимит упражнений в тренировке."],
  ["Titan", "Титан"],
  ["Too many confirmation emails were requested. Supabase may block new emails for up to an hour on the built-in sender. Try again later, or contact support if the email never arrives.", "Too many confirmation emails были requested. Supabase может блокировать новые адреса электронной почты для открытия времени в строительной форме. Try по крайней мере, или contact support if the email never arrives."],
  ["Top muscle groups", "Топ групп мышц"],
  ["Top users by XP, level and saved workouts.", "Топ пользователей по XP, уровню и тренировкам."],
  ["Total", "Всего"],
  ["Total Reps", "Всего повторов"],
  ["Total Sets", "Всего подходов"],
  ["Total Volume", "Общий объем"],
  ["Track consistency, output and intensity at a glance.", "Отслеживай стабильность, объем и интенсивность одним взглядом."],
  ["Training Profile", "Профиль тренировок"],
  ["Training goal", "Цель тренировок"],
  ["Training split", "Сплит тренировок"],
  ["Transcendent", "Трансцендентный"],
  ["Triceps Pushdown", "Разгибание рук на блоке"],
  ["Uncommon", "Необычная"],
  ["Unknown", "Неизвестно"],
  ["Unlocked", "Открыто"],
  ["Unpair Garmin", "Отсоединить Garmin"],
  ["Upper / Lower", "Верх / Низ"],
  ["Upper body", "Верх тела"],
  ["Upper/lower 4-day plan: the load leaves room for the next session.", "План верх/низ 4 дня: погрузка оставляет запас для следующей сессии."],
  ["Upright Row", "Тяга штанги к подбородку"],
  ["Use Last Weight", "Последний вес"],
  ["Use visible letters or numbers for account name.", "Используй видимые буквы или цифры для названия аккаунта."],
  ["V-Bar Triceps Pushdown", "Разгибание рук на блоке с V-рукояткой"],
  ["Vanguard", "Авангард"],
  ["View ranks", "Смотреть ранги"],
  ["View workout", "Просмотр тренировки"],
  ["Visual Trends", "Визуальные тренды"],
  ["Volume", "Объём"],
  ["Volume = weight x reps across all completed sets.", "Объем = вес x повторы по всем завершенным подходам."],
  ["Volume builder", "Покоритель объёма"],
  ["Wait for Garmin sync to finish before switching accounts.", "Дождись завершения Garmin sync перед сменой аккаунта."],
  ["Wait for Garmin sync to finish before unpairing.", "Дождитесь завершения Garmin sync перед отсоединением."],
  ["Wait for the account operation to finish.", "Дождись завершения сделки с аккаунтом."],
  ["Warborn", "Воин"],
  ["Warm Up", "Разминка"],
  ["Website", "Сайт"],
  ["Week", "Неделя"],
  ["Week streak", "Серия недель"],
  ["Weekly", "Недельные"],
  ["Weekly Missions", "Недельные миссии"],
  ["Weekly goals track this training week.", "Недельные цели считают текущую тренировочную неделю."],
  ["Weight", "Вес"],
  ["Weight (kg)", "Вес (кг)"],
  ["Weighted Crunch", "Скручивание с диском"],
  ["Weighted Side Bend", "Боковые наклоны с отягощением"],
  ["What you unlocked", "Что открыто"],
  ["Workout", "Тренировка"],
  ["Workout Details", "Детали тренировки"],
  ["Workout History", "История тренировок"],
  ["Workout Summary", "Итог тренировки"],
  ["Workout complete", "Тренировка завершена"],
  ["Workout data failed the safety checks.", "Данные тренировки не прошли проверку безопасности."],
  ["Workout date", "Дата тренировки"],
  ["Workout date is invalid.", "Дата тренировки некорректна."],
  ["Workout deleted.", "Тренировка удалена."],
  ["Workout impact", "Влияние тренировки"],
  ["Workout list", "Список тренировок"],
  ["Workout not found.", "Workout not found."],
  ["Workout plan", "Workout plan"],
  ["Workout sections", "Разделы тренировок"],
  ["Workout streak started.", "Серия тренировок начата."],
  ["Workout summary unavailable.", "Результат тренировки недоступен."],
  ["Workouts", "Тренировки"],
  ["Workouts per week", "Тренировок в неделю"],
  ["XP gained", "Получено XP"],
  ["Your XP", "Твои XP"],
  ["Your authenticated cloud row uses a legacy or invalid format. It was not loaded into the app and cannot sync until you choose a recovery action.", "Твоя авторизированная облачная запись имеет устаревший или некорректный формат. Он не загружен в приложение, и синхронизация заблокирована до выбора действия восстановления."],
  ["Your data", "Твои данные"],
  ["Your latest result and the direction of recent sessions.", "Последний результат и направление недавних тренировок."],
  ["Your training", "Твои тренировки"],
  ["Your training history and next best move.", "Твоя история тренировок и следующий лучший шаг."],
  ["d", "д"],
  ["days.", "дней."],
  ["done", "выполнено"],
  ["duration", "duration"],
  ["earned", "заработано"],
  ["exercises", "упражнений"],
  ["into this level", "в этом уровне"],
  ["kg", "кг"],
  ["kg vs first session", "кг относительно первой сессии"],
  ["left", "осталось"],
  ["light", "легко"],
  ["load", "нагрузка"],
  ["new bests", "новых рекордов"],
  ["our formula", "our formula"],
  ["peak", "peak"],
  ["sets", "подходов"],
  ["synced from Fenix 8", "synced from Fenix ​​8"],
  ["system", "system"],
  ["target", "цель"],
  ["this month", "в этом месяце"],
  ["to next", "к следующему"],
  ["to next level", "до следующего уровня"],
  ["volume", "объёма"],
  ["volume vs first session", "объема относительно первой сессии"],
  ["watch session", "watch session"],
  ["wk", "нед."],

  // Reviewed overrides for the most visible labels, validation messages, and Garmin flows.
  ["Account created. Check your email to confirm the account, then log in.", "Аккаунт создан. Подтверди адрес электронной почты, затем войди."],
  ["Add Exercise to This Workout", "Добавить упражнение в тренировку"],
  ["Add to Workout", "Добавить в тренировку"],
  ["Avg HR", "Средний пульс"],
  ["Cloud login complete.", "Вход в облачный аккаунт выполнен."],
  ["Cloud login is not configured.", "Вход в облачный аккаунт не настроен."],
  ["Cloud request failed. Check your connection and try again.", "Не удалось выполнить облачный запрос. Проверь подключение и попробуй снова."],
  ["Confirmation email sent. Check your inbox and spam folder.", "Письмо для подтверждения отправлено. Проверь входящие и папку со спамом."],
  ["Delete workout", "Удалить тренировку"],
  ["Display name can use letters, numbers, spaces, dot, dash and underscore.", "В имени можно использовать буквы, цифры, пробелы, точку, дефис и подчёркивание."],
  ["Duration", "Длительность"],
  ["Email", "Электронная почта"],
  ["Email does not match.", "Адреса электронной почты не совпадают."],
  ["Email or password is incorrect.", "Неверный адрес электронной почты или пароль."],
  ["Garmin kcal", "Garmin ккал"],
  ["Garmin strength metrics", "Метрики силовой тренировки Garmin"],
  ["Garmin strength workout", "Силовая тренировка Garmin"],
  ["Gym kcal", "Gym ккал"],
  ["Gym kcal is saved from the Garmin app strength formula. Garmin kcal is the system value Garmin Connect uses for daily calories.", "Gym ккал рассчитываются силовой формулой приложения. Garmin ккал — системное значение, которое Garmin Connect учитывает в дневных калориях."],
  ["Log in to cloud first.", "Сначала войди в облачный аккаунт."],
  ["Logged", "Записано"],
  ["Max HR", "Максимальный пульс"],
  ["New PR", "Новый рекорд"],
  ["No note", "Без заметки"],
  ["No set data", "Нет данных о подходах"],
  ["No sets", "Нет подходов"],
  ["No sets were imported for this exercise.", "Для этого упражнения не импортировано ни одного подхода."],
  ["Password must be 8-72 characters and include letters and numbers.", "Пароль должен содержать 8–72 символа, включая буквы и цифры."],
  ["Plan queued for Garmin. Open the watch app and run Cloud sync.", "План добавлен в очередь Garmin. Открой приложение на часах и запусти облачную синхронизацию."],
  ["Please fill exercises and sets first.", "Сначала добавь упражнения и подходы."],
  ["Push Pull Legs", "Жим / Тяга / Ноги"],
  ["Push day, pull day, deload...", "Жимовой день, тяговый день, разгрузка…"],
  ["Supabase is not configured.", "Supabase не настроен."],
  ["Synced sets are grouped below. Expand an exercise to edit weight, reps, add a missed set, or delete a wrong one.", "Синхронизированные подходы сгруппированы ниже. Открой упражнение, чтобы изменить вес или повторы, добавить пропущенный подход либо удалить ошибочный."],
  ["This imported workout contains exercise names, but no weights or reps. Export a full Backup JSON from the Android app and import it again.", "В импортированной тренировке есть названия упражнений, но нет веса и повторов. Экспортируй полную резервную копию JSON из Android-приложения и импортируй её снова."],
  ["Too many confirmation emails were requested. Supabase may block new emails for up to an hour on the built-in sender. Try again later, or contact support if the email never arrives.", "Запрошено слишком много писем для подтверждения. Встроенный отправитель Supabase может приостановить новые письма на срок до часа. Попробуй позже или обратись в поддержку."],
  ["Workout not found.", "Тренировка не найдена."],
  ["Workout plan", "План тренировки"],
  ["duration", "длительность"],
  ["our formula", "наша формула"],
  ["peak", "максимум"],
  ["synced from Fenix 8", "синхронизировано с Garmin"],
  ["system", "система"],
  ["watch session", "тренировка с часов"],
  ["Chest", "Грудь"],
  ["Shoulders", "Плечи"],
  ["Biceps", "Бицепс"],
  ["Triceps", "Трицепс"],
  ["Forearms", "Предплечья"],
  ["Abs", "Пресс"],
  ["Obliques", "Косые мышцы"],
  ["Upper Back", "Верхняя часть спины"],
  ["Lats", "Широчайшие"],
  ["Lower Back", "Поясница"],
  ["Glutes", "Ягодицы"],
  ["Quads", "Квадрицепсы"],
  ["Hamstrings", "Бицепс бедра"],
  ["Adductors", "Приводящие мышцы"],
  ["Calves", "Икры"],
]);

const RUSSIAN_DYNAMIC_TEXT = [
  [/^Long gap: (.+)$/, "Давно не было: $1"],
  [/^Next: (.+)$/, "Далее: $1"],
  [/^(\d+) workout XP this month\. Mission rewards are tracked separately\.$/, "$1 XP за тренировки в этом месяце. Награды миссий учитываются отдельно."],
  [/^(\d+) XP earned this month\.$/, "В этом месяце заработано $1 XP."],
  [/^(\d+) exercises today$/, "$1 упражнений сегодня"],
  [/^Log (\d+) exercise entries today\.$/, "Запиши $1 упражнений сегодня."],
  [/^(\d+)-set target$/, "Цель: $1 подходов"],
  [/^Reach (\d+) total sets today\.$/, "Выполни $1 подходов сегодня."],
  [/^Volume target (.+)$/, "Цель объёма: $1"],
  [/^Reach (.+) total volume today\.$/, "Набери объём $1 сегодня."],
  [/^Best session (.+) volume$/, "Лучшая сессия: объём $1"],
  [/^Push one session to (.+) volume today\.$/, "Доведи объём одной сессии до $1 сегодня."],
  [/^Session breadth (\d+)$/, "Упражнений в сессии: $1"],
  [/^Fit (\d+) exercises into one session today\.$/, "Выполни $1 упражнений за одну сессию сегодня."],
  [/^Session sets (\d+)$/, "Подходов в сессии: $1"],
  [/^Build one session to (\d+) sets today\.$/, "Выполни $1 подходов за одну сессию сегодня."],
  [/^(\d+)-workout week$/, "$1 тренировок за неделю"],
  [/^(\d+)-workout month$/, "$1 тренировок за месяц"],
  [/^Complete (\d+) workouts this week\.$/, "Выполни $1 тренировок на этой неделе."],
  [/^Complete (\d+) workouts this month\.$/, "Выполни $1 тренировок в этом месяце."],
  [/^(\d+) active days$/, "$1 активных дней"],
  [/^Train on (\d+) separate days this week\.$/, "Тренируйся в $1 разных дней на этой неделе."],
  [/^Train on (\d+) separate days this month\.$/, "Тренируйся в $1 разных дней в этом месяце."],
  [/^(\d+)-set week$/, "$1 подходов за неделю"],
  [/^(\d+)-set month$/, "$1 подходов за месяц"],
  [/^Reach (.+) sets this week\.$/, "Выполни $1 подходов на этой неделе."],
  [/^Reach (.+) sets this month\.$/, "Выполни $1 подходов в этом месяце."],
  [/^Weekly volume (.+)$/, "Недельный объём: $1"],
  [/^Monthly volume (.+)$/, "Месячный объём: $1"],
  [/^Reach (.+) total volume this week\.$/, "Набери объём $1 на этой неделе."],
  [/^Reach (.+) total volume this month\.$/, "Набери объём $1 в этом месяце."],
  [/^(\d+) exercises this week$/, "$1 упражнений за неделю"],
  [/^(\d+) exercises this month$/, "$1 упражнений за месяц"],
  [/^Log (\d+) exercise entries this week\.$/, "Запиши $1 упражнений на этой неделе."],
  [/^Log (\d+) exercise entries this month\.$/, "Запиши $1 упражнений в этом месяце."],
  [/^Best session (.+) sets$/, "Лучшая сессия: $1 подходов"],
  [/^Best session (.+) exercises$/, "Лучшая сессия: $1 упражнений"],
  [/^Build one session to (\d+) sets this month\.$/, "Выполни $1 подходов за одну сессию в этом месяце."],
  [/^Fit (\d+) exercises into one session this month\.$/, "Выполни $1 упражнений за одну сессию в этом месяце."]
];

window.GymRussianText = Object.freeze({
  translate(value) {
    const source = String(value);
    const exact = RUSSIAN_TEXT.get(source);
    if (exact) return exact;
    for (const [pattern, replacement] of RUSSIAN_DYNAMIC_TEXT) {
      if (pattern.test(source)) return source.replace(pattern, replacement);
    }
    return source;
  }
});
