"use strict";

const RUSSIAN_TEXT = new Map([
  ["Shared workout ready", "Общая тренировка готова"],
  ["Sign in or enter offline mode to open the editable plan. Nothing is saved until you finish and save it.", "Войдите или откройте офлайн-режим, чтобы просмотреть и изменить план. Ничего не сохранится, пока вы не завершите и не сохраните тренировку."],
  ["Workout template", "Шаблон тренировки"],
  ["Share with a friend", "Поделиться с другом"],
  ["The link contains only exercises, weights, and reps. Your account, notes, and health data stay private.", "Ссылка содержит только упражнения, веса и повторы. Аккаунт, заметки и данные о здоровье останутся приватными."],
  ["Share editable workout", "Поделиться редактируемой тренировкой"],
  ["Train together", "Тренируйтесь вместе"],
  ["Send an editable copy without account, notes, heart rate, calories, or Garmin data.", "Отправьте редактируемую копию без аккаунта, заметок, пульса, калорий и данных Garmin."],
  ["Share", "Поделиться"],
  ["Fill every exercise and set before sharing this workout.", "Заполните каждое упражнение и подход перед отправкой тренировки."],
  ["This workout cannot be shared as a template.", "Эту тренировку нельзя отправить как шаблон."],
  ["GymApp workout", "Тренировка GymApp"],
  ["Open this editable workout plan in GymApp.", "Открой этот редактируемый план тренировки в GymApp."],
  ["Workout link copied.", "Ссылка на тренировку скопирована."],
  ["Workout link ready", "Ссылка на тренировку готова"],
  ["Copy this link and send it to a friend. It opens as an editable draft and is not saved automatically.", "Скопируйте ссылку и отправьте её другу. Тренировка откроется как редактируемый черновик и не сохранится автоматически."],
  ["Copy link", "Копировать ссылку"],
  ["This workout link is invalid or too large.", "Ссылка на тренировку некорректна или слишком большая."],
  ["Assisted Dip", "Отжимания на брусьях в гравитроне"],
  ["Machine weights", "Веса тренажера"],
  ["Configured machine weights", "Настроенные веса тренажера"],
  ["Use the exact weights available on this machine.", "Укажите точные веса, доступные на этом тренажере."],
  ["Enter only the weights this machine can actually select. Smart Coach will never invent a value between them; saved history stays unchanged.", "Укажите только те веса, которые реально можно выбрать на этом тренажере. Умный тренер не будет придумывать промежуточные значения; сохраненная история не изменится."],
  ["Difficulty direction", "Направление сложности"],
  ["More kg is harder", "Больше кг — сложнее"],
  ["Less kg is harder (assistance machine)", "Меньше кг — сложнее (гравитрон)"],
  ["Quick machine-stack presets", "Быстрые шаблоны весового стека"],
  ["Selectable weights in kg", "Доступные веса в кг"],
  ["Use spaces, commas, semicolons, or new lines; use a dot for decimals. Up to 128 unique values.", "Используйте пробелы, запятые, точки с запятой или новые строки; для дробей используйте точку. До 128 уникальных значений."],
  ["Save machine weights", "Сохранить веса тренажера"],
  ["Use automatic weight steps", "Использовать автоматические шаги веса"],
  ["Enter 1 to 128 valid machine weights.", "Введите от 1 до 128 корректных весов тренажера."],
  ["Machine weights failed the safety checks.", "Веса тренажера не прошли проверку безопасности."],
  ["Machine weights saved.", "Веса тренажера сохранены."],
  ["Machine weights could not be removed.", "Не удалось удалить веса тренажера."],
  ["The configured machine stack is at its hardest boundary, so the weight is held.", "Настроенный стек тренажера уже находится на самой сложной границе, поэтому вес оставлен без изменений."],
  ["Garmin cloud watches are available after cloud sign-in.", "Облачные часы Garmin доступны после входа в облачный аккаунт."],
  ["Loading watch status…", "Загружаем статус часов…"],
  ["Retry", "Повторить"],
  ["No Garmin watch is paired with this account.", "К этому аккаунту не привязаны часы Garmin."],
  ["planned sets", "запланированных подходов"],
  ["Set intervals", "Интервалы подходов"],
  ["Chronological watch set intervals", "Хронологические интервалы подходов на часах"],
  ["Watch S1, S2, … follow completion order and may differ from the exercise grouping below.", "Подходы на часах S1, S2, … идут в порядке выполнения и могут отличаться от группировки по упражнениям ниже."],
  ["Watch", "Часы"],
  ["No timed HR zone", "Нет измеренного времени в пульсовых зонах"],
  ["Read from the workout note; imported or manually edited notes are not proof of watch origin.", "Прочитано из заметки тренировки; импортированная или изменённая вручную заметка не подтверждает происхождение с часов."],
  ["Your watch", "Ваши часы"],
  ["The browser cannot see live Bluetooth status. This shows the latest protected cloud contact from the watch.", "Браузер не видит текущее состояние Bluetooth. Здесь показан последний защищённый обмен часов с облаком."],
  ["Waiting for the first watch sync", "Ожидаем первую синхронизацию часов"],
  ["Watch synced a moment ago", "Часы только что синхронизировались"],
  ["Last watch sync", "Последняя синхронизация часов"],
  ["Paired", "Привязано"],
  ["2 / week", "2/неделя"],
  ["3 / week", "3/неделя"],
  ["4 / week", "4/неделя"],
  ["5 / week", "5/неделя"],
  ["6 / week", "6/неделя"],
  ["A fresh streak has started.", "Новая серия началась."],
  ["A verification code was sent to your email. Enter it together with the new password.", "Код подтверждения отправлен на вашу электронную почту. Введите его вместе с новым паролем."],
  ["Add image", "Добавить изображение"],
  ["Choose a JPEG, PNG, or WebP image up to 8 MB.", "Выберите изображение JPEG, PNG или WebP размером до 8 МБ."],
  ["Start · Finish", "Начало · Завершение"],
  ["Your image", "Ваше изображение"],
  ["No demonstration yet", "Демонстрации пока нет"],
  ["Choose a clear image that helps you recognize this exercise.", "Выберите понятное изображение, по которому легко узнать упражнение."],
  ["Movement guide", "Демонстрация движения"],
  ["Tap-friendly reference for exercise selection. This is not medical or coaching advice.", "Наглядная подсказка для выбора упражнения. Это не медицинская и не тренерская рекомендация."],
  ["Choose your image", "Выбрать своё изображение"],
  ["Restore built-in image", "Восстановить встроенное изображение"],
  ["The custom image could not be removed.", "Не удалось удалить пользовательское изображение."],
  ["Account deletion cancelled.", "Удаление аккаунта отменено."],
  ["Account switch was cancelled because the latest browser changes could not be synced. Try again when the connection is available.", "Переключение аккаунта отменено, потому что последние изменения в браузере не удалось синхронизировать. Попробуйте снова после восстановления соединения."],
  ["Cancel", "Отмена"],
  ["Cancel and sign out", "Отменить и выйти"],
  ["Change password", "Изменить пароль"],
  ["Choose a new password", "Выберите новый пароль"],
  ["Choose a password different from the current password.", "Выберите пароль, который отличается от текущего."],
  ["Cloud account permanently deleted.", "Облачный аккаунт удалён безвозвратно."],
  ["Cloud account is ready.", "Облачный аккаунт готов."],
  ["Cloud account was deleted, but some browser data could not be cleared. Clear site data before using this device again.", "Облачный аккаунт удалён, но часть данных браузера не удалось очистить. Очистите данные сайта перед повторным использованием этого устройства."],
  ["Cloud account deletion failed. Nothing was deleted from this browser.", "Не удалось удалить облачный аккаунт. В этом браузере ничего не удалено."],
  ["Cloud data is temporarily unavailable. Reload or retry without requesting a new email.", "Облачные данные временно недоступны. Перезагрузите страницу или повторите попытку, не запрашивая новое письмо."],
  ["Cloud state was recovered, but the public profile summary could not be updated. Try again later.", "Облачные данные восстановлены, но публичную сводку профиля не удалось обновить. Попробуйте позже."],
  ["Cloud sync needs your choice", "Для облачной синхронизации нужен ваш выбор"],
  ["Cloud sync failed. Your latest changes remain saved in this browser.", "Облачная синхронизация не удалась. Последние изменения сохранены в этом браузере."],
  ["Cloud version loaded.", "Облачная версия загружена."],
  ["Current password", "Текущий пароль"],
  ["Current password is too long.", "Текущий пароль слишком длинный."],
  ["Delete cloud account", "Удалить облачный аккаунт"],
  ["Delete local account", "Удалить локальный аккаунт"],
  ["Delete set", "Удалить подход"],
  ["Log set · rest 90 s", "Записать подход · отдых 90 с"],
  ["Add planned set", "Добавить запланированный подход"],
  ["Save as completed workout", "Сохранить как выполненную тренировку"],
  ["Sync sends these targets to the watch. Saving as completed records every row in history and opens the summary.", "Синхронизация отправляет эти цели на часы. Сохранение как выполненной записывает каждую строку в историю и открывает итог."],
  ["Could not log the set. Rest was not started.", "Не удалось записать подход. Таймер отдыха не запущен."],
  ["Rest timer could not be saved.", "Не удалось сохранить таймер отдыха."],
  ["Rest timer could not be stopped.", "Не удалось остановить таймер отдыха."],
  ["Set logged, but the rest timer could not be saved.", "Подход записан, но сохранить таймер отдыха не удалось."],
  ["Delete this exercise from your library? This cannot be undone in GymApp.", "Удалить это упражнение из каталога? В GymApp это действие нельзя отменить."],
  ["Delete this saved set? Workout totals, progress, and recommendations will be updated. This cannot be undone in GymApp.", "Удалить этот сохранённый подход? Итоги тренировки, прогресс и рекомендации будут обновлены. В GymApp это действие нельзя отменить."],
  ["Edit set", "Редактировать подход"],
  ["Enter the email for your cloud account. The reset link must be opened in this browser.", "Введите адрес электронной почты облачного аккаунта. Ссылку для сброса нужно открыть в этом браузере."],
  ["Enter your current password.", "Введите текущий пароль."],
  ["Enter the verification code from your email.", "Введите код подтверждения из письма."],
  ["Email authentication could not be saved in this browser.", "Не удалось сохранить аутентификацию по электронной почте в этом браузере."],
  ["Email confirmation could not be completed. Request a new confirmation email and try again.", "Не удалось завершить подтверждение электронной почты. Запросите новое письмо и попробуйте снова."],
  ["Email confirmed. Your cloud account is ready.", "Электронная почта подтверждена. Ваш облачный аккаунт готов."],
  ["Email verified, but cloud data is temporarily unavailable. Reload or retry without requesting a new email.", "Электронная почта подтверждена, но облачные данные временно недоступны. Перезагрузите страницу или повторите попытку, не запрашивая новое письмо."],
  ["Finishing cloud sign-in", "Завершаем вход в облачный аккаунт"],
  ["Forgot password?", "Забыли пароль?"],
  ["If an account exists for this email, a password reset link has been sent. Open the newest email in this browser.", "Если аккаунт с этим адресом существует, ссылка для сброса пароля отправлена. Откройте самое новое письмо в этом браузере."],
  ["Local account deletion failed. The account remains open; restore browser storage access and try again.", "Не удалось удалить локальный аккаунт. Он остаётся открытым; восстановите доступ к хранилищу браузера и попробуйте снова."],
  ["Local account permanently deleted from this browser.", "Локальный аккаунт безвозвратно удалён из этого браузера."],
  ["Exercise deleted.", "Упражнение удалено."],
  ["New password", "Новый пароль"],
  ["Password changed.", "Пароль изменён."],
  ["Password recovery could not be saved in this browser.", "Не удалось сохранить восстановление пароля в этом браузере."],
  ["Password reset could not be completed. Request a new reset email and try again.", "Не удалось завершить сброс пароля. Запросите новое письмо и попробуйте снова."],
  ["Password reset verified. Choose a new password to continue.", "Сброс пароля подтверждён. Выберите новый пароль, чтобы продолжить."],
  ["Permanently delete this cloud account, its workouts, profile and connected devices? This cannot be undone. Export a backup first if you need it.", "Безвозвратно удалить этот облачный аккаунт, его тренировки, профиль и подключённые устройства? Это действие нельзя отменить. При необходимости сначала экспортируйте резервную копию."],
  ["Permanently delete this local account and every workout saved for it in this browser? This cannot be undone. Export a backup first if needed.", "Безвозвратно удалить этот локальный аккаунт и все его тренировки в этом браузере? Это действие нельзя отменить. При необходимости сначала экспортируйте резервную копию."],
  ["Repeat new password", "Повторите новый пароль"],
  ["Replace profile with backup?", "Заменить профиль резервной копией?"],
  ["Replace with backup", "Заменить резервной копией"],
  ["Retry cloud loading", "Повторить загрузку из облака"],
  ["Reset password", "Сбросить пароль"],
  ["Save new password", "Сохранить новый пароль"],
  ["Secure email authentication is unavailable in this browser.", "Безопасная аутентификация по электронной почте недоступна в этом браузере."],
  ["Secure password recovery is unavailable in this browser.", "Безопасное восстановление пароля недоступно в этом браузере."],
  ["Send reset link", "Отправить ссылку для сброса"],
  ["Sign out", "Выйти"],
  ["Sign in again before changing your password.", "Войдите снова перед изменением пароля."],
  ["Sign in again before deleting this cloud account.", "Войдите снова перед удалением облачного аккаунта."],
  ["The new password does not meet the server password policy.", "Новый пароль не соответствует требованиям сервера."],
  ["The change could not be completed safely. Reload this account before making more changes.", "Не удалось безопасно завершить изменение. Перезагрузите этот аккаунт перед дальнейшими изменениями."],
  ["This confirmation is no longer current. Nothing was changed.", "Это подтверждение уже неактуально. Ничего не изменено."],
  ["This authentication link or code has expired. Request a new one.", "Срок действия ссылки или кода истёк. Запросите новый."],
  ["This confirmation link expired or could not be verified. Request a new email.", "Срок действия ссылки для подтверждения истёк или её не удалось проверить. Запросите новое письмо."],
  ["This confirmation link is invalid for this browser. Start account creation again.", "Эта ссылка для подтверждения не подходит для данного браузера. Начните создание аккаунта заново."],
  ["This password reset link expired or could not be verified. Request a new email.", "Срок действия ссылки для сброса пароля истёк или её не удалось проверить. Запросите новое письмо."],
  ["This password reset link is invalid for this browser. Request a new email here.", "Эта ссылка для сброса пароля не подходит для данного браузера. Запросите здесь новое письмо."],
  ["This import will replace workout history, exercises, mappings, and profile settings. This cannot be undone in GymApp.", "Этот импорт заменит историю тренировок, упражнения, сопоставления и настройки профиля. В GymApp это действие нельзя отменить."],
  ["Type DELETE to permanently delete the cloud account.", "Введите DELETE, чтобы безвозвратно удалить облачный аккаунт."],
  ["Type DELETE to permanently delete the local account.", "Введите DELETE, чтобы безвозвратно удалить локальный аккаунт."],
  ["Verification code", "Код подтверждения"],
  ["Verification code sent. Re-enter the new password with the code.", "Код подтверждения отправлен. Повторно введите новый пароль вместе с кодом."],
  ["Verifying email confirmation…", "Проверяем подтверждение электронной почты…"],
  ["Verifying password reset…", "Проверяем сброс пароля…"],
  ["Workouts synced, but the public profile summary could not be updated.", "Тренировки синхронизированы, но публичную сводку профиля не удалось обновить."],
  ["Your email is already verified. GymApp is loading cloud data with the saved session; no new email is needed.", "Электронная почта уже подтверждена. GymApp загружает облачные данные с помощью сохранённой сессии; новое письмо не требуется."],
  ["Your cloud session expired or was revoked. Sign in again; browser-saved workouts were kept.", "Облачная сессия завершилась или была отозвана. Войдите снова; тренировки, сохранённые в браузере, не потеряны."],
  ["Browser version saved to the cloud.", "Версия из браузера сохранена в облаке."],
  ["Discard this browser's conflicting changes and use the cloud version? Download a browser backup first. This cannot be undone in GymApp.", "Отбросить конфликтующие изменения в этом браузере и использовать облачную версию? Сначала скачайте резервную копию браузера. Это действие нельзя отменить в GymApp."],
  ["Download a backup first, then explicitly choose which version should continue.", "Сначала скачайте резервную копию, затем явно выберите, какую версию продолжить использовать."],
  ["Download browser backup", "Скачать резервную копию из браузера"],
  ["Keep browser version", "Сохранить версию из браузера"],
  ["Replace the conflicting cloud version with this browser version? Download a backup first. The revision check will stop if the cloud changes again.", "Заменить конфликтующую облачную версию версией из этого браузера? Сначала скачайте резервную копию. Проверка ревизии остановит операцию, если данные в облаке снова изменятся."],
  ["This browser and the cloud both changed since their last confirmed sync. GymApp kept the browser copy and did not overwrite either version.", "Данные и в этом браузере, и в облаке изменились после последней подтверждённой синхронизации. GymApp сохранил копию из браузера и не перезаписал ни одну из версий."],
  ["Use cloud version", "Использовать облачную версию"],
  ["Your reset link was verified. Set a new password before continuing to your cloud account.", "Ссылка для сброса подтверждена. Установите новый пароль, прежде чем продолжить работу с облачным аккаунтом."],
  ["A legacy storage-key collision was detected. Sign-in is blocked so one local account cannot open another account's data.", "Выявлена ​​коллизия старого ключа хранилища. Вход заблокирован, чтобы один локальный аккаунт не открыл данные другого."],
  ["A one-time Garmin token will be shown. It works like a password: paste it only into this watch's Connect IQ settings. GymApp will not store or show it again. Continue?", "Будет показан одноразовый токен Garmin. Он работает как пароль: вставь его только в настройку Connect IQ этих часов. GymApp не будет сохранять и не покажет его снова. Продолжить?"],
  ["A previous Garmin device creation is still awaiting revocation. Keep this page open and retry before pairing again.", "Предыдущее создание устройства Garmin всё ещё ожидает отзыва. Не закрывай эту страницу и повтори попытку перед новым сопряжением."],
  ["A previous Garmin queue result is still unknown. Start a different logical submission anyway? It may create a second plan if the earlier request succeeded. Cancel is recommended.", "Результат предыдущего Garmin-запроса еще неизвестен. Все равно начать другую отправку? Если предыдущий запрос сработал, может появиться второй план. Рекомендуется отменить."],
  ["A redacted diagnostics report is not a restorable backup.", "Обезличенный отчет диагностики не является резервной копией."],
  ["Account", "Аккаунт"],
  ["Account, data and progress", "Аккаунт, данные и прогресс"],
  ["Manage your account, connected services and protected progress in one place.", "Управляй аккаунтом, подключёнными сервисами и защищённым прогрессом в одном месте."],
  ["Security", "Безопасность"],
  ["Protected progress", "Защищённый прогресс"],
  ["Rating status", "Статус рейтинга"],
  ["Rating not available yet", "Рейтинг пока недоступен"],
  ["Workouts are currently scored on your device, so public ranking is disabled, not queued for review. It will appear only after a future app and server update adds verified scoring; no release date is set. Your private progress remains available.", "Сейчас тренировки оцениваются на устройстве, поэтому публичный рейтинг отключён, а не поставлен в очередь на проверку. Он появится только после будущего обновления приложения и сервера с проверяемым подсчётом; даты выпуска пока нет. Твой приватный прогресс остаётся доступным."],
  ["Your synced progress", "Твой синхронизированный прогресс"],
  ["Loading protected cloud progress.", "Загружаем защищённый облачный прогресс."],
  ["Showing local stats while protected cloud progress is unavailable.", "Показываем локальные данные, пока защищённый облачный прогресс недоступен."],
  ["Refresh updates only your own cloud XP. It does not start a rating check.", "Обновление загружает только твои собственные XP из облака. Оно не запускает проверку рейтинга."],
  ["Refresh progress", "Обновить прогресс"],
  ["Local mode. Sign in to protect and synchronize your progress.", "Локальный режим. Войди, чтобы защитить и синхронизировать прогресс."],
  ["Protected cloud progress is available after Supabase is configured.", "Защищённый облачный прогресс станет доступен после настройки Supabase."],
  ["No synced progress yet.", "Синхронизированного прогресса пока нет."],
  ["Could not load protected cloud progress. Try refresh again.", "Не удалось загрузить защищённый облачный прогресс. Попробуй обновить снова."],
  ["Achievement", "Достижение"],
  ["A full import replaces this profile. Manual backups include favorite exercises; cloud schema-v2 intentionally keeps favorites local to this account and device.", "Полный импорт заменяет этот профиль. Ручная резервная копия содержит избранные упражнения; облачная schema-v2 намеренно хранит их локально для этого аккаунта и устройства."],
  ["Cloud account with protected synchronization.", "Облачный аккаунт с защищённой синхронизацией."],
  ["Collection", "Коллекция"],
  ["Community", "Сообщество"],
  ["Epic", "Эпическое"],
  ["Every badge has a stable milestone and stays visible before and after unlock.", "У каждого значка есть постоянная цель, и он остаётся видимым до и после открытия."],
  ["Favorites", "Избранные"],
  ["Find setup help or review how GymApp handles your data.", "Найди помощь по настройке или узнай, как GymApp обрабатывает твои данные."],
  ["Help and trust", "Помощь и доверие"],
  ["Legendary", "Легендарное"],
  ["Local account on this device.", "Локальный аккаунт на этом устройстве."],
  ["Manage your exercise library, history, and muscle groups.", "Управляй каталогом упражнений, историей и группами мышц."],
  ["Open Garmin Connect IQ", "Открыть Garmin Connect IQ"],
  ["Open Google Play", "Открыть Google Play"],
  ["Official apps", "Официальные приложения"],
  ["Get GymApp", "Скачать GymApp"],
  ["Install the Android app or add the companion app to your Garmin watch.", "Установи приложение для Android или добавь приложение-компаньон на часы Garmin."],
  ["GET IT ON", "СКАЧАТЬ В"],
  ["AVAILABLE ON", "ДОСТУПНО В"],
  ["Privacy policy", "Политика конфиденциальности"],
  ["Profile", "Профиль"],
  ["Appearance", "Оформление"],
  ["Color theme", "Цветовая тема"],
  ["System", "Системная"],
  ["Light", "Светлая"],
  ["Dark", "Тёмная"],
  ["Follow this device or keep GymApp light or dark.", "Используй тему устройства или зафиксируй светлое либо тёмное оформление GymApp."],
  ["Support and privacy", "Поддержка и конфиденциальность"],
  ["First Workout", "Первая тренировка"],
  ["Complete your first workout.", "Заверши свою первую тренировку."],
  ["Starter Habit", "Начало привычки"],
  ["Complete five workouts.", "Заверши пять тренировок."],
  ["Consistency Builder", "Стабильный прогресс"],
  ["Complete ten workouts.", "Заверши десять тренировок."],
  ["Workhorse", "Трудяга"],
  ["Complete twenty-five workouts.", "Заверши двадцать пять тренировок."],
  ["Veteran", "Ветеран"],
  ["Complete fifty workouts.", "Заверши пятьдесят тренировок."],
  ["Centurion", "Центурион"],
  ["Complete one hundred workouts.", "Заверши сто тренировок."],
  ["Seven-Day Streak", "Серия из семи дней"],
  ["Keep a seven day streak alive.", "Поддерживай серию семь дней."],
  ["Fourteen-Day Streak", "Серия из четырнадцати дней"],
  ["Keep a fourteen day streak alive.", "Поддерживай серию четырнадцать дней."],
  ["Thirty-Day Streak", "Серия из тридцати дней"],
  ["Keep a thirty day streak alive.", "Поддерживай серию тридцать дней."],
  ["Ten Thousand Volume", "Объём 10 000"],
  ["Accumulate ten thousand total volume.", "Набери общий объём 10 000."],
  ["Fifty Thousand Volume", "Объём 50 000"],
  ["Accumulate fifty thousand total volume.", "Набери общий объём 50 000."],
  ["Comeback", "Возвращение"],
  ["Return after a seven day break.", "Вернись после семидневного перерыва."],
  ["Remove from favorites", "Убрать из избранного"],
  ["One softer session is held steady; a deload needs two comparable regressions.", "После одной более слабой тренировки нагрузка сохраняется; для разгрузки нужны два сопоставимых спада."],
  ["Two comparable regressions in a row triggered a recovery step.", "Два сопоставимых спада подряд запустили восстановительный шаг."],
  ["Four comparable sessions showed no meaningful strength, rep, or per-set volume gain.", "Четыре сопоставимые тренировки не показали заметного роста силы, повторов или объёма на подход."],
  ["Muscle-gain goal adds recoverable working volume.", "Цель набора мышц добавляет рабочий объём, который можно восстановить."],
  ["Calorie deficit trims set volume but still allows earned progression.", "Дефицит калорий сокращает число подходов, но не блокирует заслуженную прогрессию."],
  ["Calorie surplus supports an additional recoverable set.", "Профицит калорий позволяет добавить ещё один восстанавливаемый подход."],
  ["Every saved set reached the top of the rep range, so load increases conservatively.", "Каждый сохранённый подход достиг верхней границы повторов, поэтому вес увеличивается осторожно."],
  ["Calorie surplus allows progression when the completed sessions support it.", "Профицит калорий позволяет прогрессировать, когда это подтверждают выполненные тренировки."],
  ["The rep ceiling is complete; add a small external load or choose a harder variation instead of exceeding 10 reps.", "Верхняя граница повторов выполнена; добавьте небольшое отягощение или выберите более сложный вариант вместо превышения 10 повторов."],
  ["Two complete sessions reached the rep ceiling without a performance drop, so difficulty increases conservatively.", "Две полные тренировки достигли верхней границы повторов без снижения результата, поэтому сложность повышается осторожно."],
  ["Account created. Check your email to confirm the account, then log in.", "Аккаунт создан. Подтверди адрес электронной почты, затем войди."],
  ["After creating the account, we will show where the confirmation email was sent.", "После создания аккаунта мы покажем, на какой адрес отправлено письмо для подтверждения."],
  ["Back to sign in", "Вернуться ко входу"],
  ["Check your email", "Проверьте электронную почту"],
  ["Account name is too long.", "Название аккаунта слишком длинное."],
  ["Account switch was cancelled.", "Переключение аккаунта отменено."],
  ["Accumulate 10000 total volume.", "Набери общий объём 10 000."],
  ["Achievements", "Достижения"],
  ["Active daily, weekly, and monthly missions rotate from a huge challenge pool.", "Активные ежедневные, недельные и месячные миссии выбираются из пула вызовов."],
  ["Activity Heatmap", "Карта активности"],
  ["Add Exercise", "Добавить упражнение"],
  ["Add Exercise to This Workout", "Add Exercise to This Workout"],
  ["Add Set", "Добавить подход"],
  ["Add to favorites", "Добавить в избранное"],
  ["Add Workout", "Добавить тренировку"],
  ["Add a custom movement or open a saved exercise to view its history.", "Добавь собственное упражнение или открой сохраненное, чтобы просмотреть историю."],
  ["Add exercise", "Добавить упражнение"],
  ["Add sets to see chart.", "Добавь подходы, чтобы увидеть график."],
  ["Add to Workout", "Add to Workout"],
  ["Add workouts to unlock daily, weekly, and monthly goals.", "Добавь тренировки, чтобы открыть ежедневные, недельные и месячные цели."],
  ["Add your first workout to unlock smarter recommendations.", "Добавь первую тренировку, чтобы открыть более умные рекомендации."],
  ["Aesthetic Cut", "Сушка"],
  ["Aesthetic goal: the plan favors clean volume and technique.", "Цель сушки: план делает упор на качественный объём и технику."],
  ["All", "Все"],
  ["All muscles", "Все мышцы"],
  ["All saved exercises are already in this workout.", "Все сохранённые упражнения уже добавлены в эту тренировку."],
  ["All time", "За все время"],
  ["All-time best", "Лучшее за все время"],
  ["An account with this email already exists. Log in or resend the confirmation email.", "Аккаунт с этим адресом электронной почты уже существует. Войди или повторно отправь письмо для подтверждения."],
  ["An exercise or its set list is invalid.", "Упражнение или список его подходов некорректны."],
  ["An exercise with this name already exists.", "Упражнение с таким названием уже существует."],
  ["An incomplete Garmin pairing could not be revoked. Cancel to keep this cloud session and retry (recommended). Choose OK only to sign out locally; GymApp will retry cleanup after you sign back into this account.", "Не удалось отозвать незавершённое сопряжение Garmin. Нажми «Отмена», чтобы сохранить облачную сессию и повторить попытку (рекомендуется). Нажми «ОК» только для локального выхода; GymApp повторит очистку после входа в этот аккаунт."],
  ["Anonymous", "Без имени"],
  ["Apex", "Апекс"],
  ["Apply Smart Plan", "Применить план"],
  ["Ascendant", "Вознесенный"],
  ["Assisted Pull Up", "Подтягивание в гравитроне"],
  ["Auto mapping", "Автосопоставление"],
  ["Auto mapping works first, manual choices override it.", "Сначала применяется автосопоставление, а ручной выбор имеет приоритет."],
  ["Average Max", "Средний максимум"],
  ["Average volume", "Средний объем"],
  ["Avg / Set", "Сред. / подход"],
  ["Avg HR", "Avg HR"],
  ["Back", "Сзади"],
  ["Back to workouts", "К тренировкам"],
  ["Backup JSON ready", "Резервная копия JSON готова"],
  ["Backup and diagnostics", "Резервное копирование и диагностика"],
  ["Backup imported.", "Резервная копия импортирована."],
  ["Backups merge into the current profile and skip duplicate sessions.", "Резервные копии объединяются с текущим профилем и пропускают дубликаты тренировок."],
  ["Balanced", "Баланс"],
  ["Band Assisted Pull Up", "Подтягивание с эспандером"],
  ["Barbell Curl", "Сгибание рук со штангой"],
  ["Barbell Row", "Тяга штанги в наклоне"],
  ["Barbell Squat", "Присед со штангой"],
  ["Based on muscle load and recent training gaps.", "На основе нагрузки на мышцы и недавних перерывов в тренировках."],
  ["Bench Press", "Жим штанги лежа"],
  ["Best", "Лучшее"],
  ["Best Weight", "Лучший вес"],
  ["Beyond", "Сверхпредельный"],
  ["Biceps Curl", "Сгибание рук на бицепс"],
  ["Bring up", "Подтяни"],
  ["Build plan: hold weight and add reps before the next jump.", "План набора: сохраняй вес и добавляй повторы перед следующим увеличением веса."],
  ["Build today's session", "Собери сегодняшнюю тренировку"],
  ["Built-in", "Встроенное"],
  ["Bulgarian Split Squat", "Болгарские выпады"],
  ["By name", "По названию"],
  ["Cable Curl", "Сгибание рук на нижнем блоке"],
  ["Calf Raise", "Подъем на носки"],
  ["Calorie deficit: progression is more conservative to protect recovery.", "Дефицит калорий: прогрессия более осторожна для восстановления."],
  ["Calorie mode", "Режим калорий"],
  ["Celestial", "Небесный"],
  ["Challenger", "Претендент"],
  ["Check your sets, then save to move straight into workout details.", "Проверь подходы и сохрани, чтобы перейти к деталям тренировки."],
  ["Choose muscles for this exercise.", "Выбери мышцы для этого упражнения."],
  ["Clear search", "Очистить поиск"],
  ["Clipboard access is unavailable.", "Доступ к буферу обмена недоступен."],
  ["Clipboard write failed.", "Невозможно записать в буфер обмена."],
  ["Close dialog", "Закрыть диалог"],
  ["Cloud", "Облако"],
  ["Cloud account", "Облачный аккаунт"],
  ["Cloud data recovery", "Восстановление облачных данных"],
  ["Cloud login complete.", "Вход в облачный аккаунт выполнен."],
  ["Cloud login complete. Recovery action is required before sync.", "Вход в облачный аккаунт выполнен. Перед синхронизацией требуется восстановление данных."],
  ["Cloud login is not configured.", "Вход в облачный аккаунт не настроен."],
  ["Cloud login is ready after Supabase keys are added.", "Облачный вход заработает после добавления ключей Supabase."],
  ["Cloud recovery failed.", "Не удалось восстановить облачные данные."],
  ["Cloud recovery session is stale. Sign out and log in again.", "Сессия восстановления облачных данных устарела. Выйди и войди снова."],
  ["Cloud request failed. Check your connection and try again.", "Не удалось выполнить облачный запрос. Проверь подключение и попробуй снова."],
  ["Cloud state recovery completed.", "Восстановление облачного состояния завершено."],
  ["Cloud state was recovered, but protected progress could not be refreshed. Try again later.", "Облачные данные восстановлены, но защищённый прогресс не удалось обновить. Попробуй позже."],
  ["Cloud sync conflicted. Reload before saving again.", "Возник конфликт облачной синхронизации. Обнови данные перед повторным сохранением."],
  ["Cloud sync failed.", "Синхронизация не удалась."],
  ["Colors show which muscle groups carried the most load.", "Цвета показывают, какие группы мышц получили наибольшую нагрузку."],
  ["Colossus", "Колосс"],
  ["Comeback plan: restart below the last weight after a training gap.", "План возврата: начни ниже последнего веса после паузы."],
  ["Common", "Обычная"],
  ["Completed", "Выполнено"],
  ["Completed missions and new badges from this finish.", "Выполненные миссии и новые значки после завершения тренировки."],
  ["Confidence", "Уверенность"],
  ["Confirm your email first, then log in.", "Сначала подтверди адрес электронной почты, затем войди."],
  ["Confirmation email sent. Check your inbox and spam folder.", "Confirmation email sent. Check your inbox and spam folder."],
  ["Conqueror", "Завоеватель"],
  ["Consistency", "Стабильность"],
  ["Consistency milestone reached.", "Достигнута веха стабильности."],
  ["Copy JSON", "Копировать JSON"],
  ["Copy Last +2.5 kg", "Копировать последний +2,5 кг"],
  ["Copy Last Set", "Копировать подход"],
  ["Copy Previous Workout", "Скопировать предыдущую тренировку"],
  ["Copy a previous workout", "Скопировать предыдущее"],
  ["Copy this Garmin pairing token into Connect IQ settings now. Treat it as a password. It will not be stored or shown again. Choose Cancel to revoke it.", "Скопируйте этот токен Garmin в настройку Connect IQ сейчас. Относись к нему как к паролю. Он не будет храниться и больше не показываться. Нажмите «Отмена», чтобы отозвать его."],
  ["Core", "Кор"],
  ["Cosmic Warlord", "Космический воевода"],
  ["Create account", "Создать аккаунт"],
  ["Current", "Текущий"],
  ["Current level", "Текущий уровень"],
  ["Current title", "Текущий ранг"],
  ["Custom", "Собственный"],
  ["Daily", "Ежедневные"],
  ["Daily Missions", "Ежедневные миссии"],
  ["Daily consistency goals reset at midnight.", "Ежедневные цели стабильности обновляются в полночь."],
  ["Deadlift", "Становая тяга"],
  ["Deficit", "Дефицит"],
  ["Delete exercise", "Удалить упражнение"],
  ["Delete workout", "Delete workout"],
  ["Deload", "Разгрузка"],
  ["Dialog", "Диалог"],
  ["Dips", "Отжимания на брусьях"],
  ["Display name", "Имя профиля"],
  ["Display name can use letters, numbers, spaces, dot, dash and underscore.", "Display name может использовать листы, номера, пространства, dot, dash and underscore."],
  ["Dominator", "Доминатор"],
  ["Download", "Загрузить"],
  ["Download original private JSON", "Загрузить оригинальный частный JSON"],
  ["Driven", "Мотивированный"],
  ["Dumbbell Bench Press", "Жим гантелей лежа"],
  ["Duration", "Duration"],
  ["Earn XP to unlock rank titles.", "Зарабатывай XP, чтобы открывать ранги."],
  ["Edit Set", "Редактировать подход"],
  ["Elite", "Элита"],
  ["Email", "Email"],
  ["Email does not match.", "Адреса электронной почты не совпадают."],
  ["Email or password is incorrect.", "Неверный адрес электронной почты или пароль."],
  ["Empyrean", "Эмпирей"],
  ["Enter", "Войти"],
  ["Enter a valid email address.", "Введите правильный адрес электронной почты."],
  ["Enter a valid weight and whole-number reps for every set.", "Введи корректный вес и целое количество повторов для каждого подхода."],
  ["Enter account name.", "Введи название аккаунта."],
  ["Enter exercise name.", "Введи название упражнения."],
  ["Enter valid reps and optional weight.", "Введи корректные повторы и вес."],
  ["Enter your email.", "Введите свой e-mail."],
  ["Eternal", "Вечный"],
  ["Exercise", "Упражнение"],
  ["Exercise Rest", "Отдых"],
  ["Exercise library", "Каталог упражнений"],
  ["Exercise mapping", "Маппинг упражнений"],
  ["Exercise name", "Название упражнения"],
  ["Exercise name is too long.", "Название упражнения слишком длинное."],
  ["Exercises", "Упражнения"],
  ["Exercises for", "Упражнения для"],
  ["Existing Garmin recovery was cancelled. No new device identity was created.", "Восстановление существующего Garmin отменено. Новый идентификатор устройства не создан."],
  ["Export JSON", "Экспорт JSON"],
  ["Export redacted diagnostics", "Экспорт обезличенной диагностики"],
  ["Face Pull", "Тяга каната к лицу"],
  ["Fallback for this browser only.", "Запасной режим только для этого браузера."],
  ["Finish 100 total sets.", "Выполни в общей сложности 100 подходов."],
  ["Finish Workout", "Завершить"],
  ["Finish the pending Garmin recovery? This rotates a replacement token for the same watch identity and shows it once. Cancel leaves the current server token unchanged.", "Завершить неоконченное восстановление Garmin? Будет создан новый токен для того же идентификатора часов и показан один раз. \"Отменить\" не изменит действующий серверный токен."],
  ["First download the untouched private JSON for offline recovery. Replacing it with an empty valid state is permanent and uses the exact server revision so another device's newer update cannot be overwritten.", "Сначала загрузил неизмененный приватный JSON для офлайн-восстановления. Замена на пустое корректное состояние необратима и использует точную ревизию сервера, поэтому новые изменения с другого устройства не будут перезаписаны."],
  ["First logged best", "Первый зафиксированный рекорд"],
  ["First session", "Первая сессия"],
  ["First tracked session", "Первая отслеженная тренировка"],
  ["French Press", "Французский жим"],
  ["Front", "Впереди"],
  ["Full Body", "Все тело"],
  ["Galactic", "Галактический"],
  ["Garmin kcal", "Garmin kcal"],
  ["Garmin pairing revoked. Reset the watch app before creating a new pairing.", "Сопряжение Garmin отозвано. Сбрось приложение на часах перед созданием нового сопряжения."],
  ["Garmin pairing was cancelled.", "Сопряжение Garmin отменено."],
  ["Garmin strength metrics", "Garmin strength metrics"],
  ["Garmin strength workout", "Garmin strength workout"],
  ["Garmin sync is already in progress.", "Синхронизация с Garmin уже выполняется."],
  ["Garmin sync is already running in another GymApp tab. Finish it there before retrying.", "Синхронизация с Garmin уже выполняется в другой вкладке GymApp. Заверши её там перед повторной попыткой."],
  ["Garmin token rotated for the existing watch. Save it in Connect IQ settings, then sync on the watch.", "Токен Garmin обновлен для имеющихся часов. Сохрани его в настройках Connect IQ и запусти синхронизацию на часах."],
  ["Garmin token rotation completed for a stale account session. Sign back into the same account and run Sync Watch to finish recovery for this watch identity.", "Обновление токена Garmin завершено для устаревшей сессии. Войди в тот же аккаунт и снова нажми «Синхронизировать с часами», чтобы завершить восстановление этих часов."],
  ["Garmin token shown once. After saving it in Connect IQ settings, sync on the watch.", "Токен Garmin показан один раз. Сохрани его в настройках Connect IQ и запусти синхронизацию на часах."],
  ["Garmin unpair failed.", "Garmin не удалось отключить."],
  ["Generate Smart Workout", "Сгенерировать тренировку"],
  ["Gym kcal", "Gym kcal"],
  ["Gym kcal is saved from the Garmin app strength formula. Garmin kcal is the system value Garmin Connect uses for daily calories.", "Gym kcal находится в Garmin app strength formula. Garmin kcal является системным значением Garmin Connect используется для дневных calories."],
  ["GymApp links", "Ссылки GymApp"],
  ["Hammer Curl", "Молоточные сгибания рук"],
  ["Hanging Leg Raise", "Подъем ног в висе"],
  ["High", "Высокий"],
  ["Hip Adduction", "Сведение ног в тренажере"],
  ["Hip Abduction", "Разведение ног в тренажере"],
  ["Hip Thrust", "Ягодичный мост со штангой"],
  ["History", "История"],
  ["Hold a 7-day streak.", "Удержи серию 7 дней."],
  ["Holding steady", "Стабильно"],
  ["Hyperextension", "Гиперекстензия"],
  ["Immortal", "Бессмертный"],
  ["Import", "Импорт"],
  ["Import JSON", "Импорт JSON"],
  ["Import backup", "Импорт резервной копии"],
  ["In progress", "В процессе"],
  ["Incline Bench Press", "Жим штанги на наклонной скамье"],
  ["Incline Dumbbell Press", "Жим гантелей на наклонной скамье"],
  ["Infinite", "Бесконечный"],
  ["Invalid backup.", "Некорректная резервная копия."],
  ["Ironclad", "Несокрушимый"],
  ["JSON copied.", "JSON скопирован."],
  ["Keep logging to unlock more.", "Продолжай записывать тренировки, чтобы открыть больше."],
  ["LEVEL", "УРОВЕНЬ"],
  ["Last", "Последняя"],
  ["Last session was stable across the sets.", "Последняя сессия была стабильна по подходам."],
  ["Lat Pulldown", "Тяга верхнего блока"],
  ["Lateral Raise", "Подъемы гантелей через стороны"],
  ["Latest max", "Последний максимум"],
  ["Latest volume", "Последний объем"],
  ["Leaderboard", "Таблица рейтинга"],
  ["Least frequent", "Реже всего"],
  ["Leg Extension", "Разгибание ног в тренажере"],
  ["Leg Press", "Жим ногами в тренажере"],
  ["Leg day", "День ног"],
  ["Legend", "Легенда"],
  ["Less", "Меньше"],
  ["Level", "Уровень"],
  ["Level progress", "Прогресс уровня"],
  ["Load", "Нагрузка"],
  ["Loading", "Загрузка"],
  ["Local", "Локальный"],
  ["Local account could not be saved.", "Не удалось сохранить локальный аккаунт."],
  ["Local account limit reached.", "Достигнут предел локальных аккаунтов."],
  ["Locked", "Закрыто"],
  ["Log in", "Войти"],
  ["Log in instead", "Войти вместо регистрации"],
  ["Log in to cloud first.", "Найти в cloud first."],
  ["Log sets to light up the body map.", "Запиши подходы для подсветки карты тела."],
  ["Log your first workout.", "Запиши свою первую тренировку."],
  ["Log your plan fast and keep momentum with smart set shortcuts.", "Быстро запиши план и сохраняй темп с помощью удобных действий для подходов."],
  ["Logged", "Logged"],
  ["Logged today", "Записано сегодня"],
  ["Lower body", "Низ тела"],
  ["Lunge", "Выпады"],
  ["Lying Leg Curl", "Сгибание ног лежа"],
  ["Machine Chest Fly", "Сведение рук в тренажёре"],
  ["Machine Lateral Raise", "Подъемы рук через стороны в тренажере"],
  ["Maintenance", "Поддержка"],
  ["Manage your library, history, muscle groups, and backups.", "Управляй каталогом, историей, группами мышц и резервными копиями."],
  ["Map", "Маппинг"],
  ["Mapped", "Сопоставлено"],
  ["Mapped muscle load will appear after sets are saved.", "Нагрузка на мышцы появится после сохранения подходов."],
  ["Max HR", "Max HR"],
  ["Maximum weight", "Максимальный вес"],
  ["Maximum weight and session volume over time.", "Максимальный вес и объем тренировки по времени."],
  ["Mission", "Миссия"],
  ["Mission XP from completed goals", "XP миссий за выполненные цели"],
  ["Missions", "Миссии"],
  ["Momentum", "Темп"],
  ["Month", "Месяц"],
  ["Month XP", "XP за месяц"],
  ["Monthly", "Месячные"],
  ["Monthly Missions", "Месячные миссии"],
  ["Monthly Snapshot", "Итог месяца"],
  ["Monthly goals measure the whole calendar month.", "Месячные цели считают весь календарный месяц."],
  ["More", "Больше"],
  ["Most frequent", "Самые частые"],
  ["Most loaded today", "Больше всего нагружено сегодня"],
  ["Muscle Gain", "Набор мышц"],
  ["Muscle Map", "Карта мышц"],
  ["Muscle groups", "Группы мышц"],
  ["Muscle load map", "Карта нагрузки на мышцы"],
  ["Mythic", "Мифический"],
  ["Name", "Имя"],
  ["Name in English or Ukrainian", "Название на украинском или английском"],
  ["New", "Новое"],
  ["New PR", "New PR"],
  ["New sessions will appear here as soon as you log them.", "Новые тренировки появятся сразу после сохранения."],
  ["Next", "Далее"],
  ["Next suggested workout", "Следующая рекомендованная тренировка"],
  ["Next suggested workout: legs", "Следующая рекомендуемая тренировка: ноги"],
  ["Next suggested workout: pull", "Следующая рекомендованная тренировка: тяга"],
  ["Next suggested workout: push", "Следующая рекомендованная тренировка: жим"],
  ["Next title", "Следующий ранг"],
  ["No active Garmin pairing is available.", "Активное сопряжение Garmin отсутствует."],
  ["No cloud recovery data is available.", "Данные для восстановления из облака недоступны."],
  ["No data", "Нет данных"],
  ["No exercise data yet", "Еще нет данных упражнения"],
  ["No exercises yet.", "Упражнений еще нет."],
  ["No history for this exercise yet.", "Истории для этого упражнения еще нет."],
  ["No history in this month.", "Нет истории за этот месяц."],
  ["No logged exercises for this muscle in the selected period.", "В выбранном периоде этой группы еще нет упражнений."],
  ["No matching exercises.", "Упражнения по этим фильтрам не найдены."],
  ["No missions yet", "Миссий еще нет"],
  ["No new unlocks", "Новых открытий нет"],
  ["No note", "No note"],
  ["No previous workouts yet.", "Предыдущих тренировок еще нет."],
  ["No ranks yet", "Рангов еще нет"],
  ["No saved history yet, so this starts with a clean baseline.", "Истории нет, поэтому план начинается с чистой базы."],
  ["No set data", "No set data"],
  ["No sets", "No sets"],
  ["No sets were imported for this exercise.", "Не все были imported for this exercise."],
  ["No workouts in this month.", "Нет тренировок в этом месяце."],
  ["Not mapped", "Не сопоставлено"],
  ["Note", "Заметка"],
  ["Nova", "Нова"],
  ["Offline local account", "Оффлайн-аккаунт"],
  ["Omega", "Омега"],
  ["Omni", "Омни"],
  ["One exercise exceeds the set limit.", "Одно упражнение превышает предел подходов."],
  ["Open", "Открыто"],
  ["Open in Garmin Connect IQ", "Открыть в Garmin Connect IQ"],
  ["Open the full rank list and check the next unlocks.", "Открой полный список рангов и проверьте следующие открытия."],
  ["Overhead Dumbbell Triceps Extension", "Разгибание гантели над головой"],
  ["Overlord", "Властелин"],
  ["Overview", "Обзор"],
  ["Paragon", "Парагон"],
  ["Password", "Пароль"],
  ["Enter your password.", "Введи пароль."],
  ["Use at least 12 characters (up to 72 UTF-8 bytes) with lowercase and uppercase Latin letters, a number, and a supported symbol such as !, @, #, or $.", "Используй не менее 12 символов (до 72 байт UTF-8): строчную и заглавную латинские буквы, цифру и поддерживаемый спецсимвол, например !, @, # или $."],
  ["Password must contain at least 12 characters, fit within 72 UTF-8 bytes, and include a lowercase Latin letter, an uppercase Latin letter, a number, and a supported symbol.", "Пароль должен содержать не менее 12 символов, занимать не более 72 байт в UTF-8 и включать строчную и заглавную латинские буквы, цифру и поддерживаемый спецсимвол."],
  ["Passwords do not match.", "Пароли не совпадают."],
  ["Paste Supabase keys into supabase-config.js to enable real network login.", "Вставьте ключи Supabase в supabase-config.js, чтобы включить подлинный сетевой вход."],
  ["Paste exported GymApp JSON here", "Встав сюда экспортированный JSON GymApp"],
  ["Paste this replacement token into the same watch's Connect IQ settings now. The old token has stopped working. This token will not be stored or shown again.", "Вставь новый токен в настройки Connect IQ тех же часов. Старый токен уже не работает. Новый токен не будет сохранён или показан повторно."],
  ["Peak weight", "Пиковый вес"],
  ["Pending Garmin recovery was not changed.", "Незавершённое восстановление Garmin не изменено."],
  ["Permanently replace the quarantined cloud row with an empty GymApp state? Download the original JSON first if you may need its private workout history. Cancel is the safe default.", "Необратимо заменить карантинную облачную запись пустым состоянием GymApp? Сначала загрузи оригинальный JSON, если может потребоваться частная история тренировок. «Отмена» — безопасный выбор по умолчанию."],
  ["Permanently revoke this Garmin pairing? Cloud sync on the current watch will stop. Before pairing it again, reset or reinstall GymApp on the watch so it forgets the old device identity. Cancel keeps the working pairing.", "Навсегда отозвать это сопряжение Garmin? Облачная синхронизация на текущих часах остановится. Перед повторным сопряжением сбрось или переустанови GymApp на часах, чтобы удалить прежний идентификатор устройства. «Отмена» сохранит рабочее сопряжение."],
  ["Personal record", "Личный рекорд"],
  ["Personal records", "Личные рекорды"],
  ["Pick an exercise to see solo progress.", "Выбери упражнение, чтобы увидеть свой прогресс."],
  ["Plan queued for Garmin. Open the watch app and run Cloud sync.", "План нуждается в Garmin. Open the watch app and run Cloud sync."],
  ["Plan templates", "Шаблоны плана"],
  ["Plank", "Планка"],
  ["Plate Loaded Row", "Горизонтальная тяга в рычажном тренажере"],
  ["Plate Twist", "Повороты корпуса с диском"],
  ["Plateau plan: change the rep target to break the flat trend.", "План плато: изменить цель повторов, чтобы сдвинуть прогресс."],
  ["Please fill every selected set within the workout limits.", "Заполни все выбранные подходы в пределах тренировочных лимитов."],
  ["Please fill exercises and sets first.", "Please fill exercises and sets first."],
  ["Preacher Curl", "Сгибание рук на скамье Скотта"],
  ["Previous best", "Предыдущий рекорд"],
  ["Prime", "Прайм"],
  ["Privacy", "Конфиденциальность"],
  ["Progress", "Прогресс"],
  ["Progress Summary", "Итог прогресса"],
  ["Progress, goals, achievements", "Прогресс, цели, достижения"],
  ["Progression plan: small load increase with controlled reps.", "План прогрессии: небольшое увеличение веса с контролируемыми повторами."],
  ["Pull Up", "Подтягивание"],
  ["Pull day", "Тяговый день"],
  ["Push Pull Legs", "Push Pull Legs"],
  ["Push Up", "Отжимания от пола"],
  ["Push day", "Жимовой день"],
  ["Push day, pull day, deload...", "Жимовой день, тяговый день, разгрузка…"],
  ["Rank Titles", "Ранги"],
  ["Rank ladder", "Лестница рангов"],
  ["Rare", "Редкая"],
  ["Rating", "Рейтинг"],
  ["Reach ten logged workouts.", "Набери 10 записанных тренировок."],
  ["Ready", "Готово"],
  ["Rear Delt Fly", "Обратные разведения в тренажере"],
  ["Recent reps or volume dipped, so the plan stays conservative.", "Повторы или объем просели, поэтому план осторожен."],
  ["Recent unlocks and the next solo milestones.", "Последние открытия и следующие личные вехи."],
  ["Recent volume dropped compared with the previous session.", "Последний объем ниже предыдущей сессии."],
  ["Recent volume is trending up.", "Последний объем растет."],
  ["Recommendations", "Рекомендации"],
  ["Recovery JSON download failed.", "Не удалось загрузить JSON для восстановления."],
  ["Recovery plan: reduce load because the last result looked strained.", "План восстановления: снизь нагрузку, потому что последний результат был тяжёлым."],
  ["Redacted diagnostics ready", "Обезличенная диагностика готова"],
  ["Refresh", "Обновить"],
  ["Remove exercise", "Убрать упражнение"],
  ["Remove set", "Удалить подход"],
  ["Rename Exercise", "Переименовать"],
  ["Rename exercise", "Переименовать упражнение"],
  ["Repeat Last Workout", "Повторить последнее"],
  ["Repeat email", "Повтори email"],
  ["Repeat password", "Повтори пароль"],
  ["Replace cloud data with empty state", "Заменить облачные данные пустым состоянием"],
  ["Reps", "Повторения"],
  ["Required level", "Нужный уровень"],
  ["Required total XP", "Требуется XP"],
  ["Resend confirmation email", "Отправить еще раз подтверждение"],
  ["Rewards", "Награды"],
  ["Romanian Deadlift", "Румынская тяга"],
  ["Rookie", "Новичок"],
  ["Save", "Сохранить"],
  ["Save Workout", "Сохранить тренировку"],
  ["Saved accounts", "Сохраненные аккаунты"],
  ["Search exercises", "Поиск упражнений"],
  ["Seated Cable Row", "Горизонтальная тяга блока"],
  ["Seated Dumbbell Curl", "Сгибание рук с гантелями сидя"],
  ["Seated Leg Curl", "Сгибание ног сидя"],
  ["Secure cross-tab Garmin sync is unavailable in this browser. Close other GymApp tabs and use a supported browser before retrying.", "Безопасная синхронизация Garmin между вкладками в этом браузере недоступна. Закрой другие вкладки GymApp и повтори в поддерживаемом браузере."],
  ["Secure local account creation is unavailable in this browser.", "Безопасное создание локального аккаунта недоступно в этом браузере."],
  ["See every title, its level gate, and the XP needed to unlock it.", "Просмотри все ранги, нужный уровень и XP для открытия."],
  ["Select exercise", "Выбери упражнение"],
  ["Session volume", "Объем тренировки"],
  ["Sessions", "Сессии"],
  ["Set", "Подход"],
  ["Set century", "Сотня подходов"],
  ["Set deleted.", "Подход удален."],
  ["Sets", "Подходы"],
  ["Several sessions stayed near the same top weight.", "Несколько сессий держались у того же максимального веса."],
  ["Share PDF report", "PDF отчет"],
  ["Shoulder Press", "Жим над головой"],
  ["Side Hyperextension", "Боковая гиперэкстензия"],
  ["Sign in to sync workouts across devices.", "Вход для синхронизации тренировки между устройствами."],
  ["Sign out without changes", "Выйти без изменений"],
  ["Sign-out was cancelled so Garmin revocation can be retried.", "Выход отменен, чтобы можно было повторить отзыв Garmin."],
  ["Sign-out was stopped because browser account data could not be erased. The account remains open in this tab. Restore storage access and retry.", "Выход остановлен, так как не удалось удалить данные аккаунта в браузере. Аккаунт остается открытым в этой вкладке. Восстанови доступ к хранилищу и повтори попытку."],
  ["Signed out locally, but server revocation was not confirmed. That old session may remain valid until server expiry or administrative revocation.", "Локальный выход выполнен, но серверный отзыв не подтвержден. Старая сессия может действовать до завершения серверного срока или административного отзыва."],
  ["Signed out locally. An incomplete Garmin pairing still needs cleanup; sign back into the same account to retry.", "Локальный выход выполнен. Незавершённое сопряжение Garmin всё ещё требует очистки; войди снова в этот аккаунт, чтобы повторить попытку."],
  ["Singularity", "Сингулярность"],
  ["Smart Coach", "Умный коуч"],
  ["Smart Coach uses this to match your plan, goal and recovery.", "Умный коуч использует это, чтобы подобрать план, цель и восстановление."],
  ["Smart workout generated", "Умная тренировка сгенерирована"],
  ["Solo Progress", "Соло прогресс"],
  ["Sovereign", "Суверен"],
  ["Squat", "Приседания со штангой"],
  ["Starter", "Начинающий"],
  ["Starter plan", "Стартовый план"],
  ["Starter plan: build clean reps and save the first baseline.", "Стартовый план: сделай чистые повторы и сохрани первую базу."],
  ["Steady", "Стабильный"],
  ["Stop", "Стоп"],
  ["Straight Arm Pulldown", "Тяга прямых рук на верхнем блоке"],
  ["Streak", "Серия"],
  ["Streak extended to", "Серия продлена до"],
  ["Streak keeper", "Хранитель серии"],
  ["Strength", "Сила"],
  ["Striker", "Ударник"],
  ["Suggested from your recent exercise pattern and training profile.", "Подобрано по последнему паттерну упражнений и профилю тренировок."],
  ["Supabase is not configured.", "Supabase не настроен."],
  ["Support", "Поддержка"],
  ["Surplus", "Профицит"],
  ["Switch", "Изменить"],
  ["Sync Plan to Watch", "Синхронизировать с часами"],
  ["Synced sets are grouped below. Expand an exercise to edit weight, reps, add a missed set, or delete a wrong one.", "Synced sets are grouped below. Распространение на регулировку гибели, reps, add mised set, або delete a wrong one."],
  ["Synced through Supabase.", "Синхронизирован через Supabase."],
  ["TOTAL XP", "ВСЕГО XP"],
  ["Tap a workout to open its details.", "Нажмите на тренировку, чтобы открыть детали."],
  ["Target muscles", "Целевые мышцы"],
  ["Ten sessions", "Десять сессий"],
  ["The Garmin binding could not be saved, so the unseen token was revoked. Free browser storage and try again.", "Не удалось сохранить привязку Garmin, поэтому непоказанный токен отозван. Освободи место в хранилище браузера и попробуй еще раз."],
  ["The Garmin token could not be revoked. Use Unpair Garmin to retry revocation, or run Sync Watch again to rotate a replacement token for the same watch identity.", "Не удалось отозвать токен Garmin. Нажми «Отсоединить Garmin», чтобы повторить отзыв, или снова нажми «Синхронизировать с часами», чтобы обновить токен тех же часов."],
  ["The exercise catalog has reached its limit.", "Каталог упражнений достиг лимита."],
  ["The increase is intentionally conservative.", "Увеличение специально осторожно."],
  ["The pending Garmin device is no longer active. Run Sync Watch again to choose or create a pairing.", "Незавершённое устройство Garmin больше не активно. Снова нажми «Синхронизировать с часами», чтобы выбрать или создать сопряжение."],
  ["The previous Garmin request ID conflicted with server state. Start a new request ID for this submission? Cancel keeps the conflict for review.", "Предыдущий Garmin request ID конфликтует с состоянием сервера. Создать новый request ID для этой отправки? «Отменить» сохранит конфликт для проверки."],
  ["The replacement Garmin token was not confirmed. Run Sync Watch again to rotate another token for the same watch identity.", "Новый токен Garmin не подтверждён. Снова нажми «Синхронизировать с часами», чтобы обновить токен тех же часов."],
  ["The report window was blocked.", "Окно отчета заблокировано."],
  ["The unseen Garmin token could not be persisted or revoked. Keep this page open and retry Garmin sync or sign-out to revoke it.", "Непоказанный токен Garmin не удалось ни сохранить, ни отозвать. Не закрывай эту страницу и повтори синхронизацию с Garmin или выход, чтобы отозвать его."],
  ["This backup belongs to another account.", "Эта резервная копия принадлежит другому аккаунту."],
  ["This exercise has reached its set limit.", "Упражнение достигло лимита подходов."],
  ["This exercise has reached the set limit.", "Достигнут лимит подходов для упражнения."],
  ["This full backup contains private workout history and account metadata. Copy it to the system clipboard? Other apps may be able to read it.", "Полная резервная копия содержит личную историю тренировок и данные аккаунта. Скопировать её в системный буфер обмена? Другие приложения могут получить к ней доступ."],
  ["This imported workout contains exercise names, but no weights or reps. Export a full Backup JSON from the Android app and import it again.", "Это imported workout contains exercise names, но не weights or reps. Получить полный Backup JSON от Android приложения и импортировать его."],
  ["This is close to your best estimated strength for the exercise.", "Это близко к лучшей оценке силы в этом упражнении."],
  ["This legacy local account name is ambiguous. Its stored data was left untouched; rename/recover it before signing in.", "Это название старого локального аккаунта неоднозначно. Сохраненные данные не изменены; возобнови или переименуй аккаунт перед входом."],
  ["This muscle group is behind your current total load.", "Эта группа мышц отстает по текущей общей нагрузке."],
  ["This report will include the full private backup. Continue to the print dialog?", "Отчёт будет содержать полную личную резервную копию. Перейти к диалогу печати?"],
  ["This saved local account is missing its state. Nothing was created or merged automatically.", "У этого сохраненного локального аккаунта отсутствует состояние. Ничего не создано и не объединено автоматически."],
  ["This workout exceeds the supported size.", "Тренировка превышает допустимый размер."],
  ["This workout has reached its set limit.", "Тренировка достигла лимита подходов."],
  ["This workout has reached the exercise limit.", "Достигнут лимит упражнений в тренировке."],
  ["Titan", "Титан"],
  ["Too many confirmation emails were requested. Supabase may block new emails for up to an hour on the built-in sender. Try again later, or contact support if the email never arrives.", "Too many confirmation emails были requested. Supabase может блокировать новые адреса электронной почты для открытия времени в строительной форме. Try по крайней мере, или contact support if the email never arrives."],
  ["Top muscle groups", "Топ групп мышц"],
  ["Your synced XP, level and saved workouts.", "Твои синхронизированные XP, уровень и тренировки."],
  ["Total", "Всего"],
  ["Total Reps", "Всего повторов"],
  ["Total Sets", "Всего подходов"],
  ["Total Volume", "Общий объем"],
  ["Track consistency, output and intensity at a glance.", "Отслеживай стабильность, объем и интенсивность одним взглядом."],
  ["Training Profile", "Профиль тренировок"],
  ["Training goal", "Цель тренировок"],
  ["Training split", "Сплит тренировок"],
  ["Transcendent", "Трансцендентный"],
  ["Triceps Pushdown", "Разгибание рук на блоке"],
  ["Uncommon", "Необычная"],
  ["Unknown", "Неизвестно"],
  ["Unlocked", "Открыто"],
  ["Unpair Garmin", "Отсоединить Garmin"],
  ["Upper / Lower", "Верх / Низ"],
  ["Upper body", "Верх тела"],
  ["Upper/lower 4-day plan: the load leaves room for the next session.", "План «верх/низ» на 4 дня: нагрузка оставляет запас для следующей тренировки."],
  ["Upright Row", "Тяга штанги к подбородку"],
  ["Use Last Weight", "Последний вес"],
  ["Use visible letters or numbers for account name.", "Используй видимые буквы или цифры для названия аккаунта."],
  ["V-Bar Triceps Pushdown", "Разгибание рук на блоке с V-рукояткой"],
  ["Vanguard", "Авангард"],
  ["View ranks", "Смотреть ранги"],
  ["View workout", "Просмотр тренировки"],
  ["Visual Trends", "Визуальные тренды"],
  ["Volume", "Объём"],
  ["Volume = weight x reps across all completed sets.", "Объем = вес x повторы по всем завершенным подходам."],
  ["Volume builder", "Покоритель объёма"],
  ["Wait for Garmin sync to finish before switching accounts.", "Дождись завершения синхронизации с Garmin перед сменой аккаунта."],
  ["Wait for Garmin sync to finish before unpairing.", "Дождись завершения синхронизации с Garmin перед отсоединением."],
  ["Wait for the account operation to finish.", "Дождись завершения операции с аккаунтом."],
  ["Warborn", "Воин"],
  ["Warm Up", "Разминка"],
  ["Website", "Сайт"],
  ["Week", "Неделя"],
  ["Week streak", "Серия недель"],
  ["Weekly", "Недельные"],
  ["Weekly Missions", "Недельные миссии"],
  ["Weekly goals track this training week.", "Недельные цели считают текущую тренировочную неделю."],
  ["Weight", "Вес"],
  ["Weight (kg)", "Вес (кг)"],
  ["Weighted Crunch", "Скручивание с диском"],
  ["Weighted Side Bend", "Боковые наклоны с отягощением"],
  ["What you unlocked", "Что открыто"],
  ["Workout", "Тренировка"],
  ["Workout Details", "Детали тренировки"],
  ["Workout History", "История тренировок"],
  ["Workout Summary", "Итог тренировки"],
  ["Workout complete", "Тренировка завершена"],
  ["Workout data failed the safety checks.", "Данные тренировки не прошли проверку безопасности."],
  ["Workout date", "Дата тренировки"],
  ["Workout date is invalid.", "Дата тренировки некорректна."],
  ["Workout deleted.", "Тренировка удалена."],
  ["Workout impact", "Влияние тренировки"],
  ["Workout list", "Список тренировок"],
  ["Workout not found.", "Workout not found."],
  ["Workout plan", "Workout plan"],
  ["Workout sections", "Разделы тренировок"],
  ["Workout streak started.", "Серия тренировок начата."],
  ["Workout summary unavailable.", "Результат тренировки недоступен."],
  ["Workouts", "Тренировки"],
  ["Workouts per week", "Тренировок в неделю"],
  ["XP gained", "Получено XP"],
  ["Your XP", "Твои XP"],
  ["Your authenticated cloud row uses a legacy or invalid format. It was not loaded into the app and cannot sync until you choose a recovery action.", "Твоя авторизированная облачная запись имеет устаревший или некорректный формат. Он не загружен в приложение, и синхронизация заблокирована до выбора действия восстановления."],
  ["Your data", "Твои данные"],
  ["Your latest result and the direction of recent sessions.", "Последний результат и направление недавних тренировок."],
  ["Your training", "Твои тренировки"],
  ["Your training history and next best move.", "Твоя история тренировок и следующий лучший шаг."],
  ["d", "д"],
  ["days.", "дней."],
  ["done", "выполнено"],
  ["duration", "duration"],
  ["earned", "заработано"],
  ["exercises", "упражнений"],
  ["into this level", "в этом уровне"],
  ["kg", "кг"],
  ["kg vs first session", "кг относительно первой сессии"],
  ["left", "осталось"],
  ["light", "легко"],
  ["load", "нагрузка"],
  ["new bests", "новых рекордов"],
  ["our formula", "our formula"],
  ["peak", "peak"],
  ["sets", "подходов"],
  ["synced from Fenix 8", "synced from Fenix ​​8"],
  ["system", "system"],
  ["target", "цель"],
  ["this month", "в этом месяце"],
  ["to next", "к следующему"],
  ["to next level", "до следующего уровня"],
  ["volume", "объёма"],
  ["volume vs first session", "объема относительно первой сессии"],
  ["watch session", "watch session"],
  ["wk", "нед."],

  // Reviewed overrides for the most visible labels, validation messages, and Garmin flows.
  ["Account created. Check your email to confirm the account, then log in.", "Аккаунт создан. Подтверди адрес электронной почты, затем войди."],
  ["Add Exercise to This Workout", "Добавить упражнение в тренировку"],
  ["Add to Workout", "Добавить в тренировку"],
  ["Avg HR", "Средний пульс"],
  ["Cloud login complete.", "Вход в облачный аккаунт выполнен."],
  ["Cloud login is not configured.", "Вход в облачный аккаунт не настроен."],
  ["Cloud request failed. Check your connection and try again.", "Не удалось выполнить облачный запрос. Проверь подключение и попробуй снова."],
  ["Confirmation email sent. Check your inbox and spam folder.", "Письмо для подтверждения отправлено. Проверь входящие и папку со спамом."],
  ["Confirmation link sent to", "Ссылка отправлена на адрес"],
  ["Delete workout", "Удалить тренировку"],
  ["Display name can use letters, numbers, spaces, dot, dash and underscore.", "В имени можно использовать буквы, цифры, пробелы, точку, дефис и подчёркивание."],
  ["Duration", "Длительность"],
  ["Email", "Электронная почта"],
  ["Email does not match.", "Адреса электронной почты не совпадают."],
  ["Email or password is incorrect.", "Неверный адрес электронной почты или пароль."],
  ["If you cannot find it, check your Spam folder.", "Если письма нет, проверьте папку «Спам»."],
  ["Garmin kcal", "Garmin ккал"],
  ["Garmin strength metrics", "Метрики силовой тренировки Garmin"],
  ["Garmin strength workout", "Силовая тренировка Garmin"],
  ["Go back", "Назад"],
  ["Gym kcal", "Gym ккал"],
  ["Gym kcal is saved from the Garmin app strength formula. Garmin kcal is the system value Garmin Connect uses for daily calories.", "Gym ккал рассчитываются силовой формулой приложения. Garmin ккал — системное значение, которое Garmin Connect учитывает в дневных калориях."],
  ["Log in to cloud first.", "Сначала войди в облачный аккаунт."],
  ["Logged", "Записано"],
  ["Language", "Язык"],
  ["Max HR", "Максимальный пульс"],
  ["New PR", "Новый рекорд"],
  ["Next month", "Следующий месяц"],
  ["Name in English, Ukrainian, or Russian", "Название на английском, украинском или русском"],
  ["No note", "Без заметки"],
  ["No set data", "Нет данных о подходах"],
  ["No sets", "Нет подходов"],
  ["No sets were imported for this exercise.", "Для этого упражнения не импортировано ни одного подхода."],
  ["Plan queued for Garmin. Open the watch app and run Cloud sync.", "План добавлен в очередь Garmin. Открой приложение на часах и запусти облачную синхронизацию."],
  ["Please fill exercises and sets first.", "Сначала добавь упражнения и подходы."],
  ["Send email again", "Отправить письмо ещё раз"],
  ["Start account creation again.", "Начните создание аккаунта заново."],
  ["Previous month", "Предыдущий месяц"],
  ["Push Pull Legs", "Жим / Тяга / Ноги"],
  ["Push day, pull day, deload...", "Жимовой день, тяговый день, разгрузка…"],
  ["Supabase is not configured.", "Supabase не настроен."],
  ["Synced sets are grouped below. Expand an exercise to edit weight, reps, add a missed set, or delete a wrong one.", "Синхронизированные подходы сгруппированы ниже. Открой упражнение, чтобы изменить вес или повторы, добавить пропущенный подход либо удалить ошибочный."],
  ["This imported workout contains exercise names, but no weights or reps. Export a full Backup JSON from the Android app and import it again.", "В импортированной тренировке есть названия упражнений, но нет веса и повторов. Экспортируй полную резервную копию JSON из Android-приложения и импортируй её снова."],
  ["Too many confirmation emails were requested. Supabase may block new emails for up to an hour on the built-in sender. Try again later, or contact support if the email never arrives.", "Запрошено слишком много писем для подтверждения. Встроенный отправитель Supabase может приостановить новые письма на срок до часа. Попробуй позже или обратись в поддержку."],
  ["Use a different address", "Использовать другой адрес"],
  ["We sent a confirmation link to the address below. Open the newest email from GymApp and tap “Confirm email”. Then return to GymApp and sign in.", "Мы отправили ссылку для подтверждения на адрес ниже. Откройте последнее письмо от GymApp и нажмите «Подтвердить email». Затем вернитесь в GymApp и войдите."],
  ["Workout not found.", "Тренировка не найдена."],
  ["Workout plan", "План тренировки"],
  ["Daily check-in", "Ежедневная тренировка"],
  ["Exercise is used in workouts.", "Упражнение используется в тренировках."],
  ["active day", "активный день"],
  ["active days", "активных дней"],
  ["day", "день"],
  ["days", "дней"],
  ["saved session", "сохранённая тренировка"],
  ["saved sessions", "сохранённых тренировок"],
  ["session", "сессия"],
  ["sessions", "сессий"],
  ["set", "подход"],
  ["workout", "тренировка"],
  ["workouts", "тренировок"],
  ["duration", "длительность"],
  ["Garmin queue retry remains pending review.", "Повторная отправка в очередь Garmin остаётся на проверке."],
  ["Garmin sync failed. Check your connection and try again.", "Не удалось синхронизировать Garmin. Проверь подключение и попробуй снова."],
  ["our formula", "наша формула"],
  ["peak", "максимум"],
  ["synced from Fenix 8", "синхронизировано с Garmin"],
  ["synced from Garmin", "синхронизировано с Garmin"],
  ["system", "система"],
  ["watch session", "тренировка с часов"],
  ["Chest", "Грудь"],
  ["Shoulders", "Плечи"],
  ["Biceps", "Бицепс"],
  ["Triceps", "Трицепс"],
  ["Forearms", "Предплечья"],
  ["Abs", "Пресс"],
  ["Obliques", "Косые мышцы"],
  ["Upper Back", "Верхняя часть спины"],
  ["Lats", "Широчайшие"],
  ["Lower Back", "Поясница"],
  ["Glutes", "Ягодицы"],
  ["Quads", "Квадрицепсы"],
  ["Hamstrings", "Бицепс бедра"],
  ["Adductors", "Приводящие мышцы"],
  ["Calves", "Икры"],

  // Final reviewed overrides for release-visible workout, account, and Garmin copy.
  ["2 / week", "2 раза в неделю"],
  ["3 / week", "3 раза в неделю"],
  ["4 / week", "4 раза в неделю"],
  ["5 / week", "5 раз в неделю"],
  ["6 / week", "6 раз в неделю"],
  ["Copy Last Set", "Копировать последний подход"],
  ["Copy a previous workout", "Скопировать предыдущую тренировку"],
  ["Copy this Garmin pairing token into Connect IQ settings now. Treat it as a password. It will not be stored or shown again. Choose Cancel to revoke it.", "Сейчас скопируй этот токен сопряжения Garmin в настройки Connect IQ. Относись к нему как к паролю. Он не будет сохранён или показан повторно. Нажми «Отмена», чтобы отозвать его."],
  ["Existing Garmin recovery was cancelled. No new device identity was created.", "Восстановление существующего сопряжения Garmin отменено. Новый идентификатор устройства не создан."],
  ["First download the untouched private JSON for offline recovery. Replacing it with an empty valid state is permanent and uses the exact server revision so another device's newer update cannot be overwritten.", "Сначала скачай неизменённый приватный JSON для офлайн-восстановления. Замена на пустое корректное состояние необратима и использует точную ревизию сервера, поэтому новые изменения с другого устройства не будут перезаписаны."],
  ["Front", "Спереди"],
  ["Garmin unpair failed.", "Не удалось отсоединить Garmin."],
  ["Last", "Последний вес"],
  ["Maintenance", "Поддержание"],
  ["Maximum weight and session volume over time.", "Максимальный вес и объём тренировки в динамике."],
  ["No exercise data yet", "По этому упражнению пока нет данных"],
  ["No logged exercises for this muscle in the selected period.", "Для этой группы мышц в выбранном периоде нет записанных упражнений."],
  ["Open the full rank list and check the next unlocks.", "Открой полный список рангов и посмотри, что откроется дальше."],
  ["Paste exported GymApp JSON here", "Вставь сюда экспортированный JSON GymApp"],
  ["Plateau plan: change the rep target to break the flat trend.", "План выхода с плато: измени цель по повторам, чтобы преодолеть застой."],
  ["Recent reps or volume dipped, so the plan stays conservative.", "Повторы или объём снизились, поэтому план остаётся консервативным."],
  ["Recent volume dropped compared with the previous session.", "Объём последней тренировки ниже объёма предыдущей."],
  ["Repeat Last Workout", "Повторить последнюю тренировку"],
  ["Share PDF report", "Поделиться PDF-отчётом"],
  ["Sign in to sync workouts across devices.", "Войди, чтобы синхронизировать тренировки между устройствами."],
  ["Smart Coach", "Умный тренер"],
  ["Smart Coach uses this to match your plan, goal and recovery.", "Умный тренер использует эти данные, чтобы подобрать план с учётом цели и восстановления."],
  ["Solo Progress", "Личный прогресс"],
  ["Suggested from your recent exercise pattern and training profile.", "Подобрано с учётом недавних упражнений и профиля тренировок."],
  ["Switch", "Сменить аккаунт"],
  ["The increase is intentionally conservative.", "Увеличение намеренно небольшое."],
  ["The pending Garmin device is no longer active. Run Sync Watch again to choose or create a pairing.", "Ожидающее сопряжения устройство Garmin больше не активно. Снова нажми «Синхронизировать с часами», чтобы выбрать или создать сопряжение."],
  ["This legacy local account name is ambiguous. Its stored data was left untouched; rename/recover it before signing in.", "Название старого локального аккаунта неоднозначно. Его данные не изменены; восстанови или переименуй аккаунт перед входом."],
  ["Use Last Weight", "Использовать последний вес"],
  ["View workout", "Открыть тренировку"],
  ["Your authenticated cloud row uses a legacy or invalid format. It was not loaded into the app and cannot sync until you choose a recovery action.", "Твоя аутентифицированная облачная запись имеет устаревший или некорректный формат. Она не загружена в приложение, и синхронизация заблокирована до выбора способа восстановления."],
  ["Your latest result and the direction of recent sessions.", "Последний результат и динамика недавних тренировок."],
  ["into this level", "на этом уровне"],
  ["A one-time Garmin token will be shown. It works like a password: paste it only into this watch's Connect IQ settings. GymApp will not store or show it again. Continue?", "Будет показан одноразовый токен Garmin. Он работает как пароль: вставь его только в настройки Connect IQ этих часов. GymApp не сохранит и больше не покажет его. Продолжить?"],
  ["Last session was stable across the sets.", "Результаты последней тренировки были стабильными во всех подходах."],
  ["Repeat email", "Повтори адрес электронной почты"],
  ["Resend confirmation email", "Повторно отправить письмо для подтверждения"],
  ["The unseen Garmin token could not be persisted or revoked. Keep this page open and retry Garmin sync or sign-out to revoke it.", "Непоказанный токен Garmin не удалось ни сохранить, ни отозвать. Не закрывай эту страницу: повтори синхронизацию с Garmin или выйди из аккаунта, чтобы отозвать токен."],
  ["Exercises in this workout", "Упражнения в этой тренировке"],
  ["Choose movements and log the working sets you plan to complete.", "Выбери упражнения и запиши рабочие подходы, которые планируешь выполнить."],
  ["Smart Coach uses your profile and saved history to build a practical starting plan.", "Умный тренер использует твой профиль и сохранённую историю, чтобы составить практичный стартовый план."],
  ["Previous session", "Предыдущая тренировка"],
  ["Workout comparison", "Сравнение тренировок"],
  ["matching exercises", "совпадающих упражнений"],
  ["No change", "Без изменений"],
  ["Previous", "Ранее"],
  ["Workout summary", "Итог тренировки"],
  ["Current month", "Текущий месяц"],
  ["Return to current month", "Вернуться к текущему месяцу"],
  ["List", "Список"],
  ["Complete 1 workout today.", "Заверши 1 тренировку сегодня."],
  ["Workout summary unavailable.", "Сводка по тренировке недоступна."],
  ["Your training history and next best move.", "Твоя история тренировок и рекомендация, что делать дальше."],
  ["TRAINING", "ТРЕНИРОВКИ"],
  ["HISTORY", "ИСТОРИЯ"],
  ["Recent sessions", "Недавние тренировки"],
  ["View all", "Посмотреть все"],
  ["Your first session will appear here", "Здесь появится твоя первая тренировка"],
  ["Start when you are ready — there is no schedule to catch up with.", "Начинай, когда готов — здесь нет графика, который нужно догонять."],
  ["YOUR NEXT MOVE", "ТВОЙ СЛЕДУЮЩИЙ ШАГ"],
  ["Build today’s session", "Составь тренировку на сегодня"],
  ["Ready when you are. Start simple and shape the workout as you go.", "Начинай, когда готов. Собирай тренировку постепенно, в своём темпе."],
  ["week streak", "недели серии"],
  ["Start workout", "Начать тренировку"],
  ["Current training facts", "Текущие показатели тренировок"],
]);

const RUSSIAN_DYNAMIC_TEXT = [
  [/^Original Garmin result: completed (\d+) of (\d+) planned sets\.$/, "Исходный результат Garmin: выполнено $1 из $2 запланированных подходов."],
  [/^Set metric rows omitted from the bounded workout note: (\d+)\.$/, "Строк показателей подходов, не поместившихся в ограниченную заметку тренировки: $1."],
  [/^Restore the existing Garmin pairing “([\s\S]+)”\? Its old token will stop immediately, and a replacement token for the same watch identity will be shown once\. Cancel keeps the current token working\.$/, "Восстановить существующее подключение Garmin «$1»? Старый токен сразу перестанет работать, а новый токен для тех же часов будет показан один раз. Отмена сохранит текущий токен."],
  [/^Choose the existing Garmin watch to restore \(1-(\d+)\)\. Rotating its token preserves the watch identity:\n([\s\S]+)$/, "Выберите часы Garmin для восстановления (1–$1). Обновление токена сохранит идентификатор часов:\n$2"],
  [/^(\d+) days since this exercise, so the load is adjusted down\.$/, "$1 дней без этого упражнения, поэтому нагрузка снижена."],
  [/^(\d+) mapped$/, "Сопоставлено: $1"],
  [/^Log sets for ([\s\S]+) to unlock trends\.$/, "Добавь подходы для $1, чтобы открыть тренды."],
  [/^(\d+) recent sessions$/, "$1 недавних тренировок"],
  [/^Delete workout from ([\s\S]+)\?$/, "Удалить тренировку от $1?"],
  [/^High-output days (\d+)$/, "Дни высокой нагрузки: $1"],
  [/^Volume days (\d+)$/, "Дни объёмных тренировок: $1"],
  [/^Strong sessions (\d+)$/, "Сильные тренировки: $1"],
  [/^Wide sessions (\d+)$/, "Разнообразные тренировки: $1"],
  [/^Long gap: (.+)$/, "Давно не было: $1"],
  [/^Next: (.+)$/, "Далее: $1"],
  [/^(\d+) workout XP this month\. Mission rewards are tracked separately\.$/, "$1 XP за тренировки в этом месяце. Награды миссий учитываются отдельно."],
  [/^(\d+) XP earned this month\.$/, "В этом месяце заработано $1 XP."],
  [/^(\d+) exercises today$/, "$1 упражнений сегодня"],
  [/^Log (\d+) exercise entries today\.$/, "Запиши $1 упражнений сегодня."],
  [/^(\d+)-set target$/, "Цель: $1 подходов"],
  [/^Reach (\d+) total sets today\.$/, "Выполни $1 подходов сегодня."],
  [/^Volume target (.+)$/, "Цель объёма: $1"],
  [/^Reach (.+) total volume today\.$/, "Набери объём $1 сегодня."],
  [/^Best session (.+) volume$/, "Лучшая сессия: объём $1"],
  [/^Push one session to (.+) volume today\.$/, "Доведи объём одной сессии до $1 сегодня."],
  [/^Session breadth (\d+)$/, "Упражнений в сессии: $1"],
  [/^Fit (\d+) exercises into one session today\.$/, "Выполни $1 упражнений за одну сессию сегодня."],
  [/^Session sets (\d+)$/, "Подходов в сессии: $1"],
  [/^Build one session to (\d+) sets today\.$/, "Выполни $1 подходов за одну сессию сегодня."],
  [/^(\d+)-workout week$/, "$1 тренировок за неделю"],
  [/^(\d+)-workout month$/, "$1 тренировок за месяц"],
  [/^Complete (\d+) workouts this week\.$/, "Выполни $1 тренировок на этой неделе."],
  [/^Complete (\d+) workouts this month\.$/, "Выполни $1 тренировок в этом месяце."],
  [/^(\d+) active days$/, "$1 активных дней"],
  [/^Train on (\d+) separate days this week\.$/, "Тренируйся в $1 разных дней на этой неделе."],
  [/^Train on (\d+) separate days this month\.$/, "Тренируйся в $1 разных дней в этом месяце."],
  [/^(\d+)-set week$/, "$1 подходов за неделю"],
  [/^(\d+)-set month$/, "$1 подходов за месяц"],
  [/^Reach (.+) sets this week\.$/, "Выполни $1 подходов на этой неделе."],
  [/^Reach (.+) sets this month\.$/, "Выполни $1 подходов в этом месяце."],
  [/^Weekly volume (.+)$/, "Недельный объём: $1"],
  [/^Monthly volume (.+)$/, "Месячный объём: $1"],
  [/^Reach (.+) total volume this week\.$/, "Набери объём $1 на этой неделе."],
  [/^Reach (.+) total volume this month\.$/, "Набери объём $1 в этом месяце."],
  [/^Hit 10 sets on (\d+) different days this week\.$/, "Выполни 10 подходов в $1 разные дни на этой неделе."],
  [/^Hit 10 sets on (\d+) days this month\.$/, "Выполни 10 подходов в $1 дни в этом месяце."],
  [/^Reach 1,000 volume on (\d+) days this week\.$/, "Набери объём 1 000 в $1 дни на этой неделе."],
  [/^Reach 1,000 volume on (\d+) days this month\.$/, "Набери объём 1 000 в $1 дни в этом месяце."],
  [/^Finish (\d+) sessions with eight or more sets this week\.$/, "Заверши $1 тренировок с восемью или более подходами на этой неделе."],
  [/^Finish (\d+) sessions with eight or more sets this month\.$/, "Заверши $1 тренировок с восемью или более подходами в этом месяце."],
  [/^Finish (\d+) sessions with three or more exercises this week\.$/, "Заверши $1 тренировок с тремя или более упражнениями на этой неделе."],
  [/^Finish (\d+) sessions with three or more exercises this month\.$/, "Заверши $1 тренировок с тремя или более упражнениями в этом месяце."],
  [/^(\d+) exercises this week$/, "$1 упражнений за неделю"],
  [/^(\d+) exercises this month$/, "$1 упражнений за месяц"],
  [/^Log (\d+) exercise entries this week\.$/, "Запиши $1 упражнений на этой неделе."],
  [/^Log (\d+) exercise entries this month\.$/, "Запиши $1 упражнений в этом месяце."],
  [/^Best session (.+) sets$/, "Лучшая сессия: $1 подходов"],
  [/^Best session (.+) exercises$/, "Лучшая сессия: $1 упражнений"],
  [/^Push one session to (.+) volume this month\.$/, "Доведи объём одной сессии до $1 в этом месяце."],
  [/^Build one session to (\d+) sets this month\.$/, "Выполни $1 подходов за одну сессию в этом месяце."],
  [/^Fit (\d+) exercises into one session this month\.$/, "Выполни $1 упражнений за одну сессию в этом месяце."]
];

window.GymRussianText = Object.freeze({
  translate(value) {
    const source = String(value);
    const exact = RUSSIAN_TEXT.get(source);
    if (exact) return exact;
    for (const [pattern, replacement] of RUSSIAN_DYNAMIC_TEXT) {
      if (pattern.test(source)) return source.replace(pattern, replacement);
    }
    return source;
  }
});
